// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(84)]
[XdbName("gameMechanics.constructor.schemes.item.AlternativeCurrency")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AlternativeCurrency
{
    [FieldOffset(24)] public string sysName;
    [FieldOffset(36)][EnumRef(typeof(Enums.Storage))] public int storage;
    [FieldOffset(40)] public TextFileRef name;
    [FieldOffset(56)] public int maxValue;
    [FieldOffset(60)] public ResourcePointer image;
    [FieldOffset(68)] public TextFileRef description;
}
