// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(52)]
[XdbName("gameMechanics.world.ClientDataParamsResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ClientDataParamsResource
{
    [FieldOffset(20)][XdbName("params")] public Param[] @params;
    [FieldOffset(36)] public ParamViewType[] paramViewTypes;

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Param
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.ClientDataParamType))] public int type;
        [FieldOffset(8)] public WString name;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ParamViewType
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.ViewType))] public int viewType;
        [FieldOffset(8)] public string name;
    }
}
