// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(128)]
[XdbName("CreatureReplaceAnimationsAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureReplaceAnimationsAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public ResourcePointer priority;
    [FieldOffset(44)] public OnTop onTop;
    [FieldOffset(84)] public OnTop onBottom;
    [FieldOffset(124)][EnumRef(typeof(Enums.ETroopMember))] public int member;
    
    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class OnTop
    {
        [FieldOffset(4)] public bool skipAnimationIfNoReplacement;
        [FieldOffset(8)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int[] notReplacedanimations;
        [FieldOffset(24)] public AnimationsReplacement[] animationsReplacements;
        
        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class AnimationsReplacement
        {
            [FieldOffset(4)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int play;
            [FieldOffset(8)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int[] forAnimations;
        }
    }
}
