// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(64)]
[XdbName("gameMechanics.elements.skills.disassembling.DisassemblerInfo")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DisassemblerInfo
{
    [FieldOffset(24)][EnumRef(typeof(Enums.DressSlot))] public int[] slots;
    [FieldOffset(40)] public ResourcePointer resource;
    [FieldOffset(48)] public ResourcePointer[] classes;
}
