// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(492)]
[XdbName("GMUIHelper")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GMUIHelper
{
    [FieldOffset(24)] public float warningLowStatPercent;
    [FieldOffset(28)] public UnlocksSpecial unlocksSpecial;
    [FieldOffset(56)] public ResourcePointer socialNetwork;
    [FieldOffset(64)] public ResourcePointer slashCommands;
    [FieldOffset(72)] public ResourcePointer referralContentKey;
    [FieldOffset(80)] public ResourcePointer notifications;
    [FieldOffset(88)] public ResourcePointer leagueFaction;
    [FieldOffset(96)] public ResourcePointer itemMall;
    [FieldOffset(104)] public ResourcePointer interfaceMaps;
    [FieldOffset(112)] public ImpactProducerUIInfos impactProducerUIInfos;
    [FieldOffset(172)] public TextFileRef gameItemCompositNameSpace;
    [FieldOffset(188)] public EquipmentData equipmentData;
    [FieldOffset(212)] public ResourcePointer empireFaction;
    [FieldOffset(220)] public ResourcePointer[] detectors;
    [FieldOffset(236)] public DailyRule[] dailyRules;
    [FieldOffset(252)] public ResourcePointer[] currencies;
    [FieldOffset(268)] public ResourcePointer contextActions;
    [FieldOffset(276)] public ConditionEvent[] conditionEvents;
    [FieldOffset(296)] public ClassSpecificData classSpecificData;
    [FieldOffset(316)] public TextFileRef chestOpening;
    [FieldOffset(332)] public ChatFilter chatFilter;
    [FieldOffset(416)] public AuctionFilter auctionFilter;
    [FieldOffset(468)] public ResourcePointer antiSpam;
    [FieldOffset(476)] public AbilitiesAliase[] abilitiesAliases;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class UnlocksSpecial
    {
        [FieldOffset(4)] public ResourcePointer[] promotionUnlocks;
        [FieldOffset(20)] public ResourcePointer greatnessUnlock;
    }

    [StructSize(60)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ImpactProducerUIInfos
    {
        [FieldOffset(4)] public ResourcePointer spell;
        [FieldOffset(12)] public ResourcePointer other;
        [FieldOffset(20)] public ResourcePointer exploit;
        [FieldOffset(28)] public ResourcePointer buff;
        [FieldOffset(36)] public ResourcePointer barrier;
        [FieldOffset(44)] public ResourcePointer attack;
        [FieldOffset(52)] public ResourcePointer ability;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class EquipmentData
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.DressSlot))] public int[] slots;
        [FieldOffset(20)] public int presetsCount;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DailyRule
    {
        [FieldOffset(4)] public ResourcePointer quest;
        [FieldOffset(12)] public ResourcePointer faction;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ConditionEvent
    {
        [FieldOffset(4)] public NullablePointer predicate;
        [FieldOffset(8)] public string alias;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ClassSpecificData
    {
        [FieldOffset(0)] public Stalker stalker;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Stalker
        {
            [FieldOffset(4)] public Arrow[] arrows;

            [StructSize(32)]
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class Arrow
            {
                [FieldOffset(4)] public ResourcePointer shotSpell;
                [FieldOffset(12)] public ResourcePointer enchatSpell;
                [FieldOffset(20)] public string alias;
            }
        }
    }

    [StructSize(84)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ChatFilter
    {
        [FieldOffset(4)] public TextFileRef forbidden;
        [FieldOffset(20)] public TextFileRef expressions;
        [FieldOffset(36)] public TextFileRef charChange;
        [FieldOffset(52)] public TextFileRef allowedSeparators;
        [FieldOffset(68)] public TextFileRef allowed;
    }

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AuctionFilter
    {
        [FieldOffset(4)] public ItemQualitie[] itemQualities;
        [FieldOffset(20)] public ItemQualitie[] itemClasses;
        [FieldOffset(36)] public ResourcePointer defaultItemQuality;
        [FieldOffset(44)] public ResourcePointer defaultItemClass;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ItemQualitie
        {
            [FieldOffset(4)] public ResourcePointer item;
            [FieldOffset(12)] public string alias;
        }
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AbilitiesAliase
    {
        [FieldOffset(4)] public string alias;
        [FieldOffset(16)] public ResourcePointer ability;
    }
}
