// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(52)]
[XdbName("gameMechanics.elements.predicates.PredicateHasItemsCount")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PredicateHasItemsCount
{
    [FieldOffset(28)] public int totalCount;
    [FieldOffset(32)] public ResourcePointer[] items;
    [FieldOffset(48)] public bool checkDress;
    [FieldOffset(49)] public bool checkBag;
}
