// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(48)]
[XdbName("gameMechanics.elements.predicates.PredicateEquipped")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PredicateEquipped
{
    [FieldOffset(28)] public bool weaponRequired;
    [FieldOffset(32)] public ResourcePointer itemClass;
    [FieldOffset(40)][EnumRef(typeof(Enums.DressSlot))] public int dressType;
    [FieldOffset(44)][EnumRef(typeof(Enums.DressContainer))] public int dressContainer;
}
