// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(40)]
[XdbName("gameMechanics.constructor.schemes.reputation.ReputationTable")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ReputationTable
{
    [FieldOffset(24)] public Table[] table;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Table
    {
        [FieldOffset(4)] public int value;
        [FieldOffset(8)][EnumRef(typeof(Enums.ReputationLevel))] public int level;
        [FieldOffset(12)] public float buyMod;
    }
}
