// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(36)]
[XdbName("gameMechanics.elements.scalers.ScalerIf")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ScalerIf
{
    [FieldOffset(24)] public NullablePointer scalerIf;
    [FieldOffset(28)] public NullablePointer scalerElse;
    [FieldOffset(32)] public NullablePointer condition;
}
