// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(92)]
[XdbName("gameMechanics.world.gameRoot.SpellRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SpellRoot
{
    [FieldOffset(24)] public ResourcePointer switchTalentBuild;
    [FieldOffset(32)] public ResourcePointer rangeSpell;
    [FieldOffset(40)] public ResourcePointer noSpell;
    [FieldOffset(48)] public ResourcePointer meleeSpell;
    [FieldOffset(56)] public ResourcePointer hearthstoneSpell;
    [FieldOffset(64)] public ResourcePointer groupTwoEnchantedArrows;
    [FieldOffset(72)] public ResourcePointer groupFairySpells;
    [FieldOffset(80)] public ResourcePointer groupEnchantedArrow;
    [FieldOffset(88)] public int globalCooldown;
}
