// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(56)]
[XdbName("TransportVisualItem")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TransportVisualItem
{
    [FieldOffset(24)] public ReplacedTexture[] replacedTextures;
    [FieldOffset(40)] public string[] disabledGeosets;

    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ReplacedTexture
    {
        [FieldOffset(4)] public string shapeName;
        [FieldOffset(16)] public ResourcePointer replacement;
        [FieldOffset(24)] public int maskColor;
        [FieldOffset(28)] public int color;
    }
}
