// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(48)]
[XdbName("VICOverride")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VICOverride
{
    [FieldOffset(24)] public VisItem[] visItems;
    [FieldOffset(40)][EnumRef(typeof(Enums.EItemPriority))] public int itemPriority;
    [FieldOffset(44)] public bool cancelDefaultDressSlotSettings;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class VisItem
    {
        [FieldOffset(4)] public ResourcePointer visItem;
        [FieldOffset(12)][EnumRef(typeof(Enums.DressSlot))] public int dressSlot;
    }
}
