// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(68)]
[XdbName("VisTransportTemplate")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisTransportTemplate
{
    [FieldOffset(24)] public ResourcePointer transportVisObject;
    [FieldOffset(32)] public int sourceFileCRC;
    [FieldOffset(36)] public ResourcePointer shieldPowerUpEffect;
    [FieldOffset(44)] public ResourcePointer shieldPowerDownEffect;
    [FieldOffset(52)] public ResourcePointer interiorVisObject;
    [FieldOffset(60)] public ResourcePointer defaultItem;
}
