// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(256)]
[XdbName("VisualMob")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualMob
{
    [FieldOffset(24)] public ResourcePointer[] visualStates;
    [FieldOffset(40)] public NullablePointer visualScript;
    [FieldOffset(44)] public Variation variation;
    [FieldOffset(124)] public bool useVisualTweaks;
    [FieldOffset(125)] public bool useVisCharacterIntervalVisScripts;
    [FieldOffset(126)] public bool useIdleSpecial;
    [FieldOffset(128)] public float transparency;
    [FieldOffset(132)] public int timeToCorpseFadingMin;
    [FieldOffset(136)] public int timeToCorpseFadingMax;
    [FieldOffset(140)] public ResourcePointer soundVariation;
    [FieldOffset(148)] public bool skipCharacterVisualScript;
    [FieldOffset(152)] public ResourcePointer sfxArmorSet;
    [FieldOffset(160)] public float scale;
    [FieldOffset(164)] public NullablePointer mobExtension;
    [FieldOffset(168)] public ResourcePointer mobEventsScripts;
    [FieldOffset(176)] public ResourcePointer mobAnimations;
    [FieldOffset(184)] public Item[] items;
    [FieldOffset(200)] public int hitCritAnimationCooldown;
    [FieldOffset(204)] public int hitAnimationCooldown;

    [FieldOffset(208)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int fixedIdleAnimation;

    [FieldOffset(212)] public float decalScale;
    [FieldOffset(216)] public CreatureParameters creatureParameters;
    [FieldOffset(224)] public ColorCoefficients colorCoefficients;
    [FieldOffset(248)] public ResourcePointer character;

    [StructSize(80)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Variation
    {
        [FieldOffset(4)] public int skinColor;
        [FieldOffset(8)] public ResourcePointer skin;
        [FieldOffset(20)] public MorphPreset morphPreset;
        [FieldOffset(40)] public ResourcePointer hairGeoset;
        [FieldOffset(48)] public int hairColor;
        [FieldOffset(52)] public int facialColor;
        [FieldOffset(56)] public ResourcePointer facial;
        [FieldOffset(64)] public ResourcePointer face;
        [FieldOffset(72)] public ResourcePointer additionalVariation;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class MorphPreset
        {
            [FieldOffset(4)] public Value[] values;

            [StructSize(16)]
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class Value
            {
                [FieldOffset(8)] public float value;

                [FieldOffset(12)]
                [EnumRef(typeof(Enums.ModelMorphControl))]
                public int controlName;
            }
        }
    }

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Item
    {
        [FieldOffset(4)]
        [EnumRef(typeof(Enums.DressSlot))]
        public int slot;

        [FieldOffset(8)] public ResourcePointer item;
    }

    [StructSize(8)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CreatureParameters
    {
        [FieldOffset(4)] public bool disableProceduralAndColorEffects;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ColorCoefficients
    {
        [FieldOffset(4)] public float w;
        [FieldOffset(8)] public bool use;
        [FieldOffset(12)] public float r;
        [FieldOffset(16)] public float g;
        [FieldOffset(20)] public float b;
    }
}
