// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(112)]
[XdbName("WebRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WebRoot
{
    [FieldOffset(24)] public ResourcePointer webResourcesRegistry;
    [FieldOffset(32)] public ResourcePointer socialNetworksRegistry;
    [FieldOffset(40)] public ImageBrowserScript imageBrowserScript;
    [FieldOffset(80)] public ResourcePointer defaultPostContent;
    [FieldOffset(88)] public WString contentKey;
    [FieldOffset(100)] public string acceptLanguage;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ImageBrowserScript
    {
        [FieldOffset(4)] public FileRef main;
        [FieldOffset(24)] public FileRef[] dependencies;
    }
}
