// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89;

[StructSize(128)]
[XdbName("ZoneInfo")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ZoneInfo
{
    [FieldOffset(24)] public Sound reverbPreset;
    [FieldOffset(48)] public Sound music;
    [FieldOffset(72)] public ResourcePointer lights;
    [FieldOffset(80)] public float hiCutFreq;
    [FieldOffset(84)] public int ambienceTimeout;
    [FieldOffset(88)] public AmbienceParameter[] ambienceParameters;
    [FieldOffset(104)] public Sound ambience;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AmbienceParameter
    {
        [FieldOffset(4)] public float value;
        [FieldOffset(8)] public ResourcePointer parameter;
    }
}
