// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(168)]
[XdbName("AmbientSound")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AmbientSound
{
    [FieldOffset(24)] public int[] boundIndices;
    [FieldOffset(40)] public BigVector3[] boundPoints;
    [FieldOffset(56)] public double height;
    [FieldOffset(68)] public SoundInfo soundInfo;
    
    [StructSize(100)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SoundInfo
    {
        [FieldOffset(0)] public Sound2D ambience;
        [FieldOffset(24)] public AmbienceParameter[] ambienceParameters;
        [FieldOffset(40)] public int ambienceTimeout;
        [FieldOffset(44)] public float hiCutFreq;
        [FieldOffset(48)] public Sound2D music;
        [FieldOffset(72)] public Sound2D reverbPreset;
        
        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class AmbienceParameter
        {
            [FieldOffset(4)] public ResourcePointer parameter;
            [FieldOffset(12)] public float value;
        }
    }
}
