// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(76)]
[XdbName("AnimatedParameters")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AnimatedParameters
{
    [FieldOffset(24)] public Vector3[] cameraTranslate;
    [FieldOffset(40)] public Vector3[] diffuseAdd;
    [FieldOffset(56)] public Vector3[] diffuseMul;
    [FieldOffset(72)] public float fps;
}
