// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(116)]
[XdbName("gameMechanics.world.astralMob.AstralMobWorld")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AstralMobWorld
{
    [FieldOffset(24)] public NullablePointer[] parts;
    [FieldOffset(44)] public float corpulence;
    [FieldOffset(48)] public TextFileRef name;
    [FieldOffset(64)] public NullablePointer spawnLocation;
    [FieldOffset(68)] public bool manualCorpulence;
    [FieldOffset(76)] public ResourcePointer image;
    [FieldOffset(84)] public ResourcePointer quality;
    [FieldOffset(92)] public TechLevelSpecific[] techLevelSpecific;
    [FieldOffset(108)] public ResourcePointer visMob;
    
    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TechLevelSpecific
    {
        [FieldOffset(4)] public float techLevel;
        [FieldOffset(8)] public ResourcePointer visMob;
    }
}
