// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(108)]
[XdbName("gameMechanics.battleground.BattleEventMapMechanics")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class BattleEventMapMechanics
{
    [FieldOffset(24)] public Achievement[] achievements;
    [FieldOffset(40)] public Duration duration;

    [FieldOffset(64)]
    [EnumRef(typeof(Enums.MatchMakingMechanicsType))]
    public int mechanicsType;

    [FieldOffset(68)] public Duration roundDuration;
    [FieldOffset(92)] public int roundsCount;
    [FieldOffset(96)] public ResourcePointer score;
    [FieldOffset(104)] public int winCounter;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Achievement
    {
        [FieldOffset(4)] public int count;
        [FieldOffset(8)] public int finalWeight;
        [FieldOffset(12)] public ResourcePointer resource;
        [FieldOffset(20)] public int weight;
        [FieldOffset(24)] public bool showInTable;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Duration
    {
        [FieldOffset(4)] public int day;
        [FieldOffset(8)] public int hour;
        [FieldOffset(12)] public int minute;
        [FieldOffset(16)] public int ms;
        [FieldOffset(20)] public int second;
    }
}
