// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(52)]
[XdbName("CameraParametersAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CameraParametersAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public Parameters parameters;
    
    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Parameters
    {
        [FieldOffset(4)] public float fov;
        [FieldOffset(8)] public float maxDistance;
        [FieldOffset(12)] public float minDistance;
    }
}
