// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(88)]
[XdbName("CameraTrackAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CameraTrackAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public CameraPoint[] cameraPoints;
    [FieldOffset(52)] public ResourcePointer cameraRoute;
    [FieldOffset(60)] public float routeDuration;
    [FieldOffset(64)] public CameraPoint[] targetPoints;
    [FieldOffset(80)] public ResourcePointer targetRoute;

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CameraPoint
    {
        [FieldOffset(4)] public float duration;
        [FieldOffset(8)] public Vector3 position;
    }
}
