// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(120)]
[XdbName("gameMechanics.world.avatar.CharacterClass")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterClass
{
    [FieldOffset(24)][XdbName("Name")] public TextFileRef name;
    [FieldOffset(40)] public string className;
    [FieldOffset(52)] public float hitDice;
    [FieldOffset(56)] public ItemClasse[] itemClasses;
    [FieldOffset(72)] public float manaDice;
    [FieldOffset(76)][EnumRef(typeof(Enums.ManaType))] public int manaType;
    [FieldOffset(80)] public ResourcePointer[] sharedAbilities;
    [FieldOffset(96)] public ResourcePointer[] sharedSpells;
    [FieldOffset(112)] public ResourcePointer talentsTable;
    
    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ItemClasse
    {
        [FieldOffset(4)] public ResourcePointer itemClass;
        [FieldOffset(12)] public int minLevel;
    }
}
