// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(80)]
[XdbName("gameMechanics.world.avatar.Character")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Character
{
    [FieldOffset(24)] public ResourcePointer characterRaceClass;
    [FieldOffset(32)] public ResourcePointer characterSex;
    [FieldOffset(40)] public ResourcePointer characterType;
    [FieldOffset(48)] public DressItem[] dressItems;
    [FieldOffset(64)] public Growth[] growths;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DressItem
    {
        [FieldOffset(4)] public ResourcePointer item;

        [FieldOffset(12)]
        [EnumRef(typeof(Enums.DressSlot))]
        public int slot;
    }

    [StructSize(116)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Growth
    {
        [FieldOffset(4)] public string chargenAnimationLoop;
        [FieldOffset(16)] public string chargenAnimationNewEquipment;
        [FieldOffset(28)] public string chargenAnimationStart;
        [FieldOffset(40)] public ChargenDressedItem[] chargenDressedItems;
        [FieldOffset(56)] public ChargenEffect[] chargenEffects;
        [FieldOffset(72)] public int level;
        [FieldOffset(76)] public Mount mount;

        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ChargenDressedItem
        {
            [FieldOffset(4)] public ResourcePointer item;

            [FieldOffset(12)]
            [EnumRef(typeof(Enums.DressSlot))]
            public int slot;
        }

        [StructSize(32)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ChargenEffect
        {
            [FieldOffset(4)] public string locator;

            [FieldOffset(16)]
            [EnumRef(typeof(Enums.ChargenEffectRunType))]
            public int runType;

            [FieldOffset(20)] public float scale;
            [FieldOffset(24)] public ResourcePointer visObj;
        }

        [StructSize(40)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Mount
        {
            [FieldOffset(4)] public string chargenAnimationLoop;
            [FieldOffset(16)] public string chargenAnimationStart;
            [FieldOffset(28)] public float scale;
            [FieldOffset(32)] public ResourcePointer visualMount;
        }
    }
}
