// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(64)]
[XdbName("gameMechanics.constructor.schemes.collectionEditions.CollectionEditionResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CollectionEditionResource
{
    [FieldOffset(28)] public CreatureVisAction[] creatureVisActions;
    [FieldOffset(44)] public NullablePointer itemsEdition;
    [FieldOffset(48)] public VisObjectTemplate[] visObjectTemplates;

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CreatureVisAction
    {
        [FieldOffset(4)] public ResourcePointer alias;
        [FieldOffset(12)] public ResourcePointer resource;
    }

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class VisObjectTemplate
    {
        [FieldOffset(4)] public ResourcePointer alias;
        [FieldOffset(12)] public ResourcePointer nextAlias;
        [FieldOffset(20)] public ResourcePointer resource;
    }
}
