// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(124)]
[XdbName("CreatureChannelDirectAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureChannelDirectAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public NullablePointer alternativeEndPoint;
    [FieldOffset(40)] public NullablePointer alternativeStartPoint;
    [FieldOffset(44)] public ResourcePointer channelingFx;
    [FieldOffset(52)] public NullablePointer endPoint;
    [FieldOffset(56)] public int fadeInTime;
    [FieldOffset(60)] public int fadeOutTime;
    [FieldOffset(64)] public float fxLength;
    [FieldOffset(68)][EnumRef(typeof(Enums.MultyTargetChannelMode))] public int multyTargetMode;
    [FieldOffset(72)] public NullablePointer offendTime;
    [FieldOffset(76)] public SecondaryTargetParams secondaryTargetParams;
    [FieldOffset(112)] public NullablePointer startPoint;
    [FieldOffset(116)] public float velocity;
    [FieldOffset(120)] public bool scaleTextureU;
    [FieldOffset(121)] public bool scaleTextureV;
    
    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SecondaryTargetParams
    {
        [FieldOffset(4)] public ResourcePointer channelingFx;
        [FieldOffset(12)] public int fadeInTime;
        [FieldOffset(16)] public int fadeOutTime;
        [FieldOffset(20)] public float fxLength;
        [FieldOffset(24)] public NullablePointer offendTime;
        [FieldOffset(28)] public float velocity;
        [FieldOffset(32)] public bool scaleTextureU;
        [FieldOffset(33)] public bool scaleTextureV;
    }
}
