// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(80)]
[XdbName("CreatureColorAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureColorAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)][EnumRef(typeof(Enums.BlendMode))] public int blendMode;
    [FieldOffset(40)] public Quaternion colorFactor;
    [FieldOffset(56)] public int colorValue;
    [FieldOffset(60)] public int priority;
    [FieldOffset(64)] public float timeOff;
    [FieldOffset(68)] public float timeOn;
    [FieldOffset(72)][EnumRef(typeof(Enums.ERiderMember))] public int useOn;
    [FieldOffset(76)] public bool ignoreDisable;
}
