// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(92)]
[XdbName("CreatureFixedTimeProjectileAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureFixedTimeProjectileAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public ResourcePointer explosionFx;
    [FieldOffset(44)] public NullablePointer offendTime;
    [FieldOffset(48)] public float optionalSpeed;
    [FieldOffset(52)] public NullablePointer pointOnCaster;
    [FieldOffset(56)] public NullablePointer pointOnTarget;
    [FieldOffset(60)] public ResourcePointer projectileFx;
    [FieldOffset(68)] public float theGe;
    [FieldOffset(72)] public bool isInverted;
    [FieldOffset(73)] public bool isMultyProjectile;
    [FieldOffset(80)] public int count;
    [FieldOffset(84)] public int throwDuration;
    [FieldOffset(88)] public int waitDuration;
}
