// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(96)]
[XdbName("fight.scheme.FightFinderRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class FightFinderRoot
{
    [FieldOffset(24)] public ResourcePointer damageDone;
    [FieldOffset(32)] public ResourcePointer damageFriendDone;
    [FieldOffset(40)] public ResourcePointer damageResisted;
    [FieldOffset(48)] public ResourcePointer damageShieldDone;
    [FieldOffset(56)] public ResourcePointer damageShieldFriendDone;
    [FieldOffset(64)] public ResourcePointer healDone;
    [FieldOffset(72)] public ResourcePointer healSelfDone;
    [FieldOffset(80)] public ResourcePointer killsDone;
    [FieldOffset(88)] public ResourcePointer killsFriendDone;
}
