// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(216)]
[XdbName("gameMechanics.elements.skills.foraging.ForagingResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ForagingResource
{
    [FieldOffset(28)] public ContextActionInfo contextActionInfo;
    [FieldOffset(76)] public ResourcePointer[] groups;
    [FieldOffset(92)] public ResourcePointer[] interruptsActionGroups;
    [FieldOffset(112)] public TextFileRef description;
    [FieldOffset(128)] public int forageSkillCheckMin;
    [FieldOffset(132)] public ResourcePointer image;
    [FieldOffset(140)] public TextFileRef name;
    [FieldOffset(156)] public ResourcePointer rerollCurrency;
    [FieldOffset(164)] public int scorePerCharacterLevel;
    [FieldOffset(168)] public ResourcePointer skillSlot;
    [FieldOffset(176)] public string sysName;
    [FieldOffset(188)][EnumRef(typeof(Enums.SkillType))] public int type;
    [FieldOffset(192)] public long zoneCooldown;
    [FieldOffset(200)] public bool hide;
    [FieldOffset(201)] public bool useLevels;
    
    [StructSize(48)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ContextActionInfo
    {
        [FieldOffset(4)] public TextFileRef contextDescription;
        [FieldOffset(20)] public ResourcePointer contextImage;
        [FieldOffset(28)] public TextFileRef contextName;
        [FieldOffset(44)] public int priority;
    }
}
