// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(156)]
[XdbName("GameViewActionMeleeAttack")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GameViewActionMeleeAttack
{
    [FieldOffset(20)] public PlaybackParameters playbackParameters;
    [FieldOffset(88)] public string offenderCreature;
    [FieldOffset(100)] public ResourcePointer producer;
    [FieldOffset(108)] public string targetCreature;
    [FieldOffset(124)] public int damageAbsorbed;
    [FieldOffset(128)] public int damageBlocked;
    [FieldOffset(132)][EnumRef(typeof(Enums.SubElement))] public int element;
    [FieldOffset(136)][EnumRef(typeof(Enums.DamageSource))] public int source;
    [FieldOffset(140)] public bool isCritical;
    [FieldOffset(141)] public bool isDamageDealt;
    [FieldOffset(142)] public bool isLethal;
    [FieldOffset(143)] public bool isOverkill;
    [FieldOffset(148)] public int damageParried;
    [FieldOffset(152)] public bool isCrushingBlow;
    [FieldOffset(153)] public bool isDodged;
    [FieldOffset(154)] public bool isGlancingBlow;
    
    [StructSize(68)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PlaybackParameters
    {
        [FieldOffset(4)] public int delayBefore;
        [FieldOffset(8)] public int repeatAfter;
        [FieldOffset(12)] public int repeatCount;
        [FieldOffset(16)] public Report report;
        [FieldOffset(60)] public bool skip;
        
        [StructSize(44)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Report
        {
            [FieldOffset(4)] public InfoString[] infoStrings;
            [FieldOffset(20)] public FileRef rtfFile;
            [FieldOffset(40)] public bool clear;
            [FieldOffset(41)] public bool skip;
            
            [StructSize(20)]
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class InfoString
            {
                [FieldOffset(4)] public string message;
                [FieldOffset(16)] public bool skip;
            }
        }
    }
}
