// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(168)]
[XdbName("gameMechanics.elements.goals.GoalResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GoalResource
{
    [FieldOffset(24)] public ResourcePointer customFinishData;
    [FieldOffset(32)] public TextFileRef description;
    [FieldOffset(48)] public NullablePointer[] finishPredicates;
    [FieldOffset(64)] public Location[] locations;
    [FieldOffset(80)] public Reward[] rewards;
    [FieldOffset(96)] public TextFileRef shortDescription;
    [FieldOffset(112)] public NullablePointer[] showPredicates;
    [FieldOffset(128)] public ResourcePointer[] stages;
    [FieldOffset(144)] public int targetLevel;
    [FieldOffset(148)] public TextFileRef title;
    [FieldOffset(164)] public bool hideInQuestBook;
    [FieldOffset(165)] public bool hideOnLoadingScreen;
    [FieldOffset(166)] public bool isHideCompleted;

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Location
    {
        [FieldOffset(4)] public Locator locator;
        [FieldOffset(48)] public NullablePointer predicate;

        [StructSize(44)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Locator
        {
            [FieldOffset(4)] public BigVector3 position;
            [FieldOffset(28)] public float radius;
            [FieldOffset(32)] public ResourcePointer zone;
            [FieldOffset(40)] public bool isIndoor;
        }
    }

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Reward
    {
        [FieldOffset(4)] public TextFileRef description;
        [FieldOffset(20)] public ResourcePointer image;
        [FieldOffset(28)] public TextFileRef name;
    }
}
