// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(88)]
[XdbName("gameMechanics.world.social.guild.base.GuildTalentFieldResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GuildTalentFieldResource
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public ResourcePointer image;
    [FieldOffset(48)] public TextFileRef name;
    [FieldOffset(64)] public Row[] rows;
    [FieldOffset(80)] public int startColumn;
    [FieldOffset(84)] public int startRow;
    
    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Row
    {
        [FieldOffset(4)] public NullablePointer[] talents;
    }
}
