// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(152)]
[XdbName("gameMechanics.world.social.guild.base.GuildAbilityResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GuildAbilityResource
{
    [FieldOffset(28)] public DescVar[] descVars;
    [FieldOffset(44)] public TextFileRef description;
    [FieldOffset(60)] public string groupName;
    [FieldOffset(72)] public int groupQuality;
    [FieldOffset(76)] public ResourcePointer image;
    [FieldOffset(84)] public TextFileRef name;
    [FieldOffset(100)] public ResourcePointer[] ranks;
    [FieldOffset(116)] public TextFileRef shortDescription;
    [FieldOffset(132)] public ResourcePointer[] spells;
    [FieldOffset(148)] public bool useGuildBunchForCalcer;
    
    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DescVar
    {
        [FieldOffset(4)] public string name;
        [FieldOffset(16)] public NullablePointer scaler;
        [FieldOffset(20)] public TextFileRef text;
        [FieldOffset(36)] public float value;
    }
}
