// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(40)]
[XdbName("HaloTable")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class HaloTable
{
    [FieldOffset(24)] public Halo[] halo;
    
    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Halo
    {
        [FieldOffset(4)] public Level[] levels;
        [FieldOffset(20)] public ResourcePointer race;
        [FieldOffset(28)][EnumRef(typeof(Enums.SlotName))] public int slot;
        [FieldOffset(32)][EnumRef(typeof(Enums.SlotName))] public int zodiacSignSlot;
        
        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Level
        {
            [FieldOffset(4)] public int level;
            [FieldOffset(8)] public ResourcePointer visual;
        }
    }
}
