// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(152)]
[XdbName("InterfaceMapQuests")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class InterfaceMapQuests
{
    [FieldOffset(24)] public ResourcePointer[] lowQuests;
    [FieldOffset(40)] public ResourcePointer[] lowQuestsEmpireOnly;
    [FieldOffset(56)] public ResourcePointer[] lowQuestsLeagueOnly;
    [FieldOffset(72)] public ResourcePointer[] lowQuestsPridenOnly;
    [FieldOffset(88)] public ResourcePointer[] quests;
    [FieldOffset(104)] public ResourcePointer[] questsEmpireOnly;
    [FieldOffset(120)] public ResourcePointer[] questsLeagueOnly;
    [FieldOffset(136)] public ResourcePointer[] questsPridenOnly;
}
