// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(80)]
[XdbName("InterfaceInvokeTargetSale")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class InterfaceInvokeTargetSale
{
    [FieldOffset(24)] public ResourcePointer alternativeItem;
    [FieldOffset(32)] public int amount;
    [FieldOffset(40)] public long duration;
    [FieldOffset(48)] public ResourcePointer item;
    [FieldOffset(56)][EnumRef(typeof(Enums.SaleTag))] public int tag;
    [FieldOffset(60)] public TextFileRef text;
}
