// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(40)]
[XdbName("itemService.basicInterfaces.itemmall.resources.ItemMallCouponsRegistry")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ItemMallCouponsRegistry
{
    [FieldOffset(24)] public Coupon[] coupons;

    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Coupon
    {
        [FieldOffset(4)] public ResourcePointer coupon;
        [FieldOffset(12)] public Item[] items;
        [FieldOffset(28)] public bool invisibleWithoutCoupon;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Item
        {
            [FieldOffset(4)] public ResourcePointer item;
            [FieldOffset(12)] public int stackCount;
            [FieldOffset(16)] public bool bound;
        }
    }
}
