// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(36)]
[XdbName("gameMechanics.tools.LinearInterpolation")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class LinearInterpolation
{
    [FieldOffset(20)] public Point[] points;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Point
    {
        [FieldOffset(4)] public float first;
        [FieldOffset(8)] public float second;
    }
}
