// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(56)]
[XdbName("gameMechanics.world.gameRoot.MentorRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class MentorRoot
{
    [FieldOffset(24)] public ItemReward[] itemReward;
    [FieldOffset(40)] public MoneyReward[] moneyReward;

    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ItemReward
    {
        [FieldOffset(4)] public ByLevelWeek[] byLevelWeek;
        [FieldOffset(20)] public ResourcePointer[] items;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ByLevelWeek
        {
            [FieldOffset(4)] public float fraction;
            [FieldOffset(8)] public int minLevel;
            [FieldOffset(12)] public int minWeek;
            [FieldOffset(16)] public float sameGuildMult;
        }
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class MoneyReward
    {
        [FieldOffset(4)] public float fraction;
        [FieldOffset(8)] public int minLevel;
        [FieldOffset(12)] public int minWeek;
        [FieldOffset(16)] public float sameGuildMult;
    }
}
