// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(124)]
[XdbName("gameMechanics.world.gameRoot.MountRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class MountRoot
{
    [FieldOffset(24)] public ResourcePointer damageThresholdResource;
    [FieldOffset(32)] public ResourcePointer dismountGroup;
    [FieldOffset(40)] public ResourcePointer exoMountGroup;
    [FieldOffset(48)] public int experiencePerDayCap;
    [FieldOffset(52)] public ResourcePointer foodCurrency;
    [FieldOffset(60)] public float hungryDiscountFactor;
    [FieldOffset(64)] public float hungryPrepareDurationFactor;
    [FieldOffset(68)] public int maxGrade;
    [FieldOffset(72)] public int maxLevel;
    [FieldOffset(76)] public int maxSatiationTime;
    [FieldOffset(80)] public MetamorphSwitchCost metamorphSwitchCost;
    [FieldOffset(96)] public ResourcePointer mountedBuffsGroup;
    [FieldOffset(104)] public ResourcePointer mountedSpellsGroup;
    [FieldOffset(112)] public int singleFeedSatiationTime;
    [FieldOffset(116)] public ResourcePointer slotCurrency;
    
    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class MetamorphSwitchCost
    {
        [FieldOffset(4)] public ResourcePointer currency;
        [FieldOffset(12)] public int value;
    }
}
