// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(96)]
[XdbName("NamedWebResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class NamedWebResource
{
    [FieldOffset(24)] public string name;
    [FieldOffset(36)] public WebResource webResource;
    
    [StructSize(60)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class WebResource
    {
        [FieldOffset(4)] public string externalUrl;
        [FieldOffset(16)] public InternalFile internalFile;
        [FieldOffset(56)] public bool isExternalResource;
        
        [StructSize(40)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class InternalFile
        {
            [FieldOffset(4)] public FileRef[] dependencies;
            [FieldOffset(20)] public FileRef main;
        }
    }
}
