// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(128)]
[XdbName("basement.server.lang.NameRules")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class NameRules
{
    [FieldOffset(40)] public AvatarNameRules avatarNameRules;
    [FieldOffset(84)] public WString country;
    [FieldOffset(96)] public NullablePointer guildNameRules;
    [FieldOffset(100)] public WString lang;
    [FieldOffset(112)] public WString name;
    [FieldOffset(124)] public NullablePointer shipNameRules;
    
    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AvatarNameRules
    {
        [FieldOffset(4)] public WString matchUser;
        [FieldOffset(16)] public int maxLength;
        [FieldOffset(20)] public int minLength;
        [FieldOffset(24)][EnumRef(typeof(Enums.NameTransformation))] public int transformation;
        [FieldOffset(32)] public WString matchMaster;
    }
}
