// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(56)]
[XdbName("Notifications")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Notifications
{
    [FieldOffset(24)][XdbName("GuildCannotHaveSymbolics")] public ResourcePointer guildCannotHaveSymbolics;
    [FieldOffset(32)][XdbName("HasNoRight")] public ResourcePointer hasNoRight;
    [FieldOffset(40)][XdbName("ItemCannotUpdateSymbolics")] public ResourcePointer itemCannotUpdateSymbolics;
    [FieldOffset(48)][XdbName("NotInGuild")] public ResourcePointer notInGuild;
}
