// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(52)]
[XdbName("ObjectCameraSettings")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ObjectCameraSettings
{
    [FieldOffset(24)] public float maxPitch;
    [FieldOffset(28)] public float maxYaw;
    [FieldOffset(32)] public float maxZoomDistance;
    [FieldOffset(36)] public float minPitch;
    [FieldOffset(40)] public float minZoomDistance;
    [FieldOffset(44)] public float zoomSpeed;
    [FieldOffset(48)] public float zoomStep;
}
