// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(72)]
[XdbName("PropertiesOfCreatureAnimations")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PropertiesOfCreatureAnimations
{
    [FieldOffset(24)] public ResourcePointer breakSheathAnimations;
    [FieldOffset(32)] public Fallback[] fallbacks;
    [FieldOffset(48)] public ResourcePointer lookAtTargetAnimations;
    [FieldOffset(56)] public ResourcePointer meleeAttackAnimations;
    [FieldOffset(64)] public ResourcePointer visualDismount;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Fallback
    {
        [FieldOffset(4)]
        [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
        public int animation;

        [FieldOffset(8)]
        [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
        public int[] fallbackAnimations;
    }
}
