// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(420)]
[XdbName("gameMechanics.constructor.schemes.quest.QuestResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class QuestResource
{
    [FieldOffset(28)] public TextFileRef checkText;
    [FieldOffset(44)] public NullablePointer clientParams;
    [FieldOffset(48)] public NullablePointer[] counters;
    [FieldOffset(64)] public TextFileRef finishText;
    [FieldOffset(80)] public NullablePointer finisher;
    [FieldOffset(84)] public TextFileRef goal;
    [FieldOffset(100)] public ResourcePointer[] groups;
    [FieldOffset(116)] public ResourcePointer image;
    [FieldOffset(124)] public WString internalName;
    [FieldOffset(136)] public TextFileRef kickText;
    [FieldOffset(152)] public NullablePointer level;
    [FieldOffset(156)] public LootTable[] lootTable;
    [FieldOffset(172)] public TextFileRef name;
    [FieldOffset(188)] public string plotline;
    [FieldOffset(200)] public NullablePointer repeatPolicy;
    [FieldOffset(204)] public NullablePointer requiredLevel;
    [FieldOffset(208)] public ReturnLocation returnLocation;
    [FieldOffset(252)] public Reward reward;
    [FieldOffset(352)] public Sharing sharing;
    [FieldOffset(360)] public NullablePointer[] startConditions;
    [FieldOffset(376)] public TextFileRef startText;
    [FieldOffset(392)][EnumRef(typeof(Enums.QuestType))] public int type;
    [FieldOffset(396)] public int uiPriority;
    [FieldOffset(400)] public ResourcePointer zone;
    [FieldOffset(408)] public bool canBeSkipped;
    [FieldOffset(409)] public bool canCancel;
    [FieldOffset(410)] public bool forInstance;
    [FieldOffset(411)] public bool hideLevel;
    [FieldOffset(412)] public bool isAutomatic;
    [FieldOffset(413)] public bool isLocationProgress;
    [FieldOffset(414)] public bool itemMall;
    [FieldOffset(415)] public bool lowPriority;
    [FieldOffset(416)] public bool pvp;
    [FieldOffset(417)] public bool secretSequence;
    [FieldOffset(418)] public bool tutorial;
    
    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class LootTable
    {
        [FieldOffset(4)] public ResourcePointer item;
        [FieldOffset(12)] public ResourcePointer lootable;
    }
    
    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ReturnLocation
    {
        [FieldOffset(4)] public BigVector3 position;
        [FieldOffset(28)] public float radius;
        [FieldOffset(32)] public ResourcePointer zone;
        [FieldOffset(40)] public bool isIndoor;
    }
    
    [StructSize(100)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Reward
    {
        [FieldOffset(4)] public AlternativeItem[] alternativeItems;
        [FieldOffset(20)] public Currencie[] currencies;
        [FieldOffset(36)] public int experience;
        [FieldOffset(40)] public NullablePointer guildAuthorityScaler;
        [FieldOffset(44)] public NullablePointer guildLoyaltyCalcer;
        [FieldOffset(48)] public AlternativeItem[] mandatoryItems;
        [FieldOffset(64)] public int money;
        [FieldOffset(68)] public Reputation[] reputations;
        [FieldOffset(84)] public ResourcePointer[] unlocks;
        
        [StructSize(28)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class AlternativeItem
        {
            [FieldOffset(4)] public NullablePointer item;
            [FieldOffset(8)] public int number;
            [FieldOffset(12)] public NullablePointer[] predicates;
        }
        
        [StructSize(32)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Currencie
        {
            [FieldOffset(4)] public ResourcePointer currency;
            [FieldOffset(12)] public NullablePointer[] predicates;
            [FieldOffset(28)] public int value;
        }
        
        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Reputation
        {
            [FieldOffset(4)] public ResourcePointer faction;
            [FieldOffset(12)] public int value;
        }
    }
    
    [StructSize(8)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Sharing
    {
        [FieldOffset(4)] public bool onRequest;
        [FieldOffset(5)] public bool onStart;
    }
}
