// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(344)]
[XdbName("avatarPopulation.service.impl.matchMakingImpl.eventType.lfg.RaidEventType")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class RaidEventType
{
    [FieldOffset(24)] public int activeEventJoinPeriod;
    [FieldOffset(28)] public int capacity;
    [FieldOffset(32)] public ResourcePointer category;
    [FieldOffset(40)] public DescVar[] descVars;
    [FieldOffset(56)] public TextFileRef description;
    [FieldOffset(72)] public TextFileRef difficulty;
    [FieldOffset(88)][EnumRef(typeof(Enums.LFGEventDifficulty))] public int difficultyMode;
    [FieldOffset(92)] public float immediatelyStartFactor;
    [FieldOffset(96)] public InviteTimeout inviteTimeout;
    [FieldOffset(120)] public NullablePointer[] joinConditions;
    [FieldOffset(136)] public int maxVisitsPerDay;
    [FieldOffset(140)] public int maxVisitsPerWeek;
    [FieldOffset(144)] public NullablePointer minAvatarLevel;
    [FieldOffset(148)] public int minAvatarsCount;
    [FieldOffset(152)] public TextFileRef name;
    [FieldOffset(168)] public Reward reward;
    [FieldOffset(268)] public NullablePointer[] showPredicates;
    [FieldOffset(284)] public ResourcePointer startTime;
    [FieldOffset(292)] public ResourcePointer ticket;
    [FieldOffset(300)][EnumRef(typeof(Enums.UnionType))] public int unionType;
    [FieldOffset(304)] public bool canDenyParticipation;
    [FieldOffset(305)] public bool commonShard;
    [FieldOffset(306)] public bool exclusive;
    [FieldOffset(307)][XdbName("internal")] public bool @internal;
    [FieldOffset(308)] public bool isHighPriority;
    [FieldOffset(309)] public bool leaderOnly;
    [FieldOffset(316)] public int maxServerProgress;
    [FieldOffset(320)] public ResourcePointer requiredCurrency;
    [FieldOffset(328)] public ResourcePointer requiredItem;
    [FieldOffset(336)] public bool leaderDepartOnly;
    [FieldOffset(337)] public bool soloMode;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DescVar
    {
        [FieldOffset(4)] public string name;
        [FieldOffset(16)] public NullablePointer scaler;
        [FieldOffset(20)] public TextFileRef text;
        [FieldOffset(36)] public float value;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class InviteTimeout
    {
        [FieldOffset(4)] public int day;
        [FieldOffset(8)] public int hour;
        [FieldOffset(12)] public int minute;
        [FieldOffset(16)] public int ms;
        [FieldOffset(20)] public int second;
    }

    [StructSize(100)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Reward
    {
        [FieldOffset(4)] public AlternativeItem[] alternativeItems;
        [FieldOffset(20)] public Currencie[] currencies;
        [FieldOffset(36)] public int experience;
        [FieldOffset(40)] public NullablePointer guildAuthorityScaler;
        [FieldOffset(44)] public NullablePointer guildLoyaltyCalcer;
        [FieldOffset(48)] public AlternativeItem[] mandatoryItems;
        [FieldOffset(64)] public int money;
        [FieldOffset(68)] public Reputation[] reputations;
        [FieldOffset(84)] public ResourcePointer[] unlocks;

        [StructSize(28)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class AlternativeItem
        {
            [FieldOffset(4)] public NullablePointer item;
            [FieldOffset(8)] public int number;
            [FieldOffset(12)] public NullablePointer[] predicates;
        }

        [StructSize(32)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Currencie
        {
            [FieldOffset(4)] public ResourcePointer currency;
            [FieldOffset(12)] public NullablePointer[] predicates;
            [FieldOffset(28)] public int value;
        }

        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Reputation
        {
            [FieldOffset(4)] public ResourcePointer faction;
            [FieldOffset(12)] public int value;
        }
    }
}
