// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(60)]
[XdbName("gameMechanics.elements.skills.reforge.ReforgeCraftResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ReforgeCraftResource
{
    [FieldOffset(24)] public NullablePointer[] available;
    [FieldOffset(40)] public Entrie[] entries;
    [FieldOffset(56)] public int variationsCount;

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Entrie
    {
        [FieldOffset(4)] public Components components;
        [FieldOffset(28)] public NullablePointer[] predicates;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Components
        {
            [FieldOffset(4)] public Component[] components;
            [FieldOffset(20)] public NullablePointer moneyRequired;

            [StructSize(32)]
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class Component
            {
                [FieldOffset(4)] public NullablePointer[] conditions;
                [FieldOffset(20)] public int count;
                [FieldOffset(24)] public ResourcePointer item;
            }
        }
    }
}
