// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(88)]
[XdbName("Sound2DTassel")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Sound2DTassel
{
    [FieldOffset(24)] public Sound2D reverbPreset;
    [FieldOffset(48)] public Sound2D sound;
    [FieldOffset(72)] public SoundParameter[] soundParameters;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SoundParameter
    {
        [FieldOffset(4)] public ResourcePointer parameter;
        [FieldOffset(12)] public float value;
    }
}
