// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(72)]
[XdbName("gameMechanics.world.worldDrop.SuffixNamer")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SuffixNamer
{
    [FieldOffset(24)] public Item[] items;
    [FieldOffset(40)][EnumRef(typeof(Enums.NamePart))] public int[] name;
    [FieldOffset(56)] public Prefixe[] prefixes;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Item
    {
        [FieldOffset(4)] public ResourcePointer baseItem;
        [FieldOffset(12)] public QualityPrefixe[] qualityPrefixes;

        [StructSize(28)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class QualityPrefixe
        {
            [FieldOffset(4)] public TextFileRef prefix;
            [FieldOffset(20)] public ResourcePointer quality;
        }
    }

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Prefixe
    {
        [FieldOffset(4)] public int level;
        [FieldOffset(8)] public Prefix prefix;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Prefix
        {
            [FieldOffset(4)] public TextFileRef value;
        }
    }
}
