// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(48)]
[XdbName("gameMechanics.constructor.schemes.talent.TalentAbility")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TalentAbility
{
    [FieldOffset(20)] public NullablePointer parentTalent;
    [FieldOffset(24)] public ResourcePointer unlock;
    [FieldOffset(32)] public bool isRecommended;
    [FieldOffset(40)] public ResourcePointer ability;
}
