// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(52)]
[XdbName("TextureSingleElement")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TextureSingleElement
{
    [FieldOffset(24)] public ResourcePointer atlas;
    [FieldOffset(32)] public int height;
    [FieldOffset(36)] public ResourcePointer key;
    [FieldOffset(44)] public int sourceFileCRC;
    [FieldOffset(48)] public int width;
}
