// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(48)]
[XdbName("TextureAtlas")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TextureAtlas
{
    [FieldOffset(24)] public ResourcePointer combinedTexture;
    [FieldOffset(32)] public Source[] sources;

    [StructSize(48)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Source
    {
        [FieldOffset(4)] public int height;
        [FieldOffset(8)] public string name;
        [FieldOffset(20)] public int width;
        [FieldOffset(24)] public int x;
        [FieldOffset(28)] public float xCoeffA;
        [FieldOffset(32)] public float xCoeffRGB;
        [FieldOffset(36)] public int y;
        [FieldOffset(40)] public float yCoeffA;
        [FieldOffset(44)] public float yCoeffRGB;
    }
}
