// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(48)]
[XdbName("gameMechanics.world.bigAstral.TierLevel")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TierLevel
{
    [FieldOffset(24)] public ResourcePointer parent;
    [FieldOffset(32)] public ResourcePointer quality;
    [FieldOffset(40)] public float requiredUnlock;
    [FieldOffset(44)] public int techLevel;
}
