// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(68)]
[XdbName("TrailTemplate")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TrailTemplate
{
    [FieldOffset(24)] public int color;
    [FieldOffset(28)] public NullablePointer colorDescriptor;
    [FieldOffset(32)] public int decayTime;
    [FieldOffset(36)] public int fadeInTimeMSec;
    [FieldOffset(40)] public int fadeOutTimeMSec;
    [FieldOffset(44)] public float speedEnd;
    [FieldOffset(48)] public float speedStart;
    [FieldOffset(52)] public float stretchSpeed;
    [FieldOffset(56)] public int texCoordsPeriodMs;
    [FieldOffset(60)] public ResourcePointer trailTexture;
}
