// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(260)]
[XdbName("UIOption")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UIOption
{
    [FieldOffset(24)] public ResourcePointer[] contentKeyDenied;
    [FieldOffset(40)] public ResourcePointer[] contentKeyRequired;
    [FieldOffset(56)][EnumRef(typeof(Enums.UIOptionDataType))] public int dataType;
    [FieldOffset(60)] public int defaultIndex;
    [FieldOffset(64)] public TextFileRef description;
    [FieldOffset(80)] public TextFileRef maxDescription;
    [FieldOffset(96)] public TextFileRef maxName;
    [FieldOffset(112)] public float maxRangeValue;
    [FieldOffset(116)] public TextFileRef minDescription;
    [FieldOffset(132)] public TextFileRef minName;
    [FieldOffset(148)] public float minRangeValue;
    [FieldOffset(152)] public TextFileRef name;
    [FieldOffset(168)] public string sysCodeId;
    [FieldOffset(180)] public string sysCustomId;
    [FieldOffset(192)] public string sysCustomType;
    [FieldOffset(204)] public string sysGlobalVarId;
    [FieldOffset(216)] public TextFileRef useAttemptWarning;
    [FieldOffset(232)] public int valueCount;
    [FieldOffset(236)] public Value[] values;
    [FieldOffset(252)][EnumRef(typeof(Enums.UIOptionViewType))] public int viewType;
    [FieldOffset(256)] public bool isSendEvent;
    [FieldOffset(257)] public bool needPreview;
    [FieldOffset(258)] public bool restartToApply;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Value
    {
        [FieldOffset(4)] public TextFileRef description;
        [FieldOffset(20)] public float floatValue;
        [FieldOffset(24)] public TextFileRef name;
    }
}
