// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(176)]
[XdbName("UIState")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UIState
{
    [FieldOffset(24)][XdbName("Addons")] public ResourcePointer[] addons;
    [FieldOffset(40)][XdbName("MainAddonName")] public string mainAddonName;
    [FieldOffset(52)][XdbName("MainForm")] public ResourcePointer mainForm;
    [FieldOffset(60)][XdbName("Name")] public string name;
    [FieldOffset(72)] public ResourcePointer aliasVisObjects;
    [FieldOffset(80)] public ResourcePointer decalObjects;
    [FieldOffset(88)] public ResourcePointer sounds;
    [FieldOffset(96)] public SoundsGroup[] soundsGroups;
    [FieldOffset(112)] public ResourcePointer texts;
    [FieldOffset(120)] public TextsGroup[] textsGroups;
    [FieldOffset(136)] public ResourcePointer textures;
    [FieldOffset(144)] public TexturesGroup[] texturesGroups;
    [FieldOffset(160)] public ResourcePointer visActions;
    [FieldOffset(168)] public ResourcePointer visObjects;
    
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SoundsGroup
    {
        [FieldOffset(4)] public string groupName;
        [FieldOffset(16)] public ResourcePointer sounds;
    }
    
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextsGroup
    {
        [FieldOffset(4)] public string groupName;
        [FieldOffset(16)] public ResourcePointer texts;
    }
    
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TexturesGroup
    {
        [FieldOffset(4)] public string groupName;
        [FieldOffset(16)] public ResourcePointer textures;
    }
}
