// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(48)]
[XdbName("gameMechanics.vessel.scheme.VesselRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VesselRoot
{
    [FieldOffset(24)] public ResourcePointer experience;
    [FieldOffset(32)] public SubElementModifier[] subElementModifiers;

    [StructSize(4)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SubElementModifier
    {
    }
}
