// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(36)]
[XdbName("VICBattleAnim")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VICBattleAnim
{
    [FieldOffset(24)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int storeAnim;

    [FieldOffset(28)] public float storeDelay;

    [FieldOffset(32)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int takeAnim;
}
