// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(336)]
[XdbName("VisualMountClass")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualMountClass
{
    [FieldOffset(24)] public AnimationSettings animationSettings;
    [FieldOffset(88)] public ControlParameters controlParameters;
    [FieldOffset(128)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int dismountAnimation;
    [FieldOffset(132)] public FxSettings fxSettings;
    [FieldOffset(152)][EnumRef(typeof(Enums.DressSlot))] public int[] hiddenDressSlots;
    [FieldOffset(168)] public JumpSettings jumpSettings;
    [FieldOffset(192)] public ResourcePointer levelChangedScript;
    [FieldOffset(200)] public PitchParameters pitchParameters;
    [FieldOffset(240)] public ReinsSettings reinsSettings;
    [FieldOffset(308)][EnumRef(typeof(Enums.ERiderOrientation))] public int riderOrientation;
    [FieldOffset(312)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int sitAnimation;
    [FieldOffset(316)] public ResourcePointer skinChangedScript;
    [FieldOffset(324)] public ResourcePointer summonVisualScript;
    [FieldOffset(332)] public bool nonDismountable;
    [FieldOffset(333)] public bool useRiderSpineTurn;
    
    [StructSize(64)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AnimationSettings
    {
        [FieldOffset(4)] public ComplexAnimation[] complexAnimations;
        [FieldOffset(20)] public ResourcePointer playOnMount;
        [FieldOffset(28)] public ResourcePointer playOnRider;
        [FieldOffset(36)] public ResourcePointer playOnRiderTopOnly;
        [FieldOffset(44)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int[] visualDismount;
        
        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ComplexAnimation
        {
            [FieldOffset(4)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int animation;
            [FieldOffset(8)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int playOnMount;
            [FieldOffset(12)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int playOnRiderBottom;
            [FieldOffset(16)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int playOnRiderTop;
        }
    }
    
    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ControlParameters
    {
        [FieldOffset(0)] public SpeedFactorBackward speedFactorBackward;
        [FieldOffset(20)] public SpeedFactorBackward speedFactorForward;
        
        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class SpeedFactorBackward
        {
            [FieldOffset(4)] public float startTime;
            [FieldOffset(8)] public float startVelocity;
            [FieldOffset(12)] public float stopTime;
            [FieldOffset(16)] public float stopVelocity;
        }
    }
    
    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class FxSettings
    {
        [FieldOffset(4)] public string[] mountLocators;
    }
    
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class JumpSettings
    {
        [FieldOffset(4)] public float jumpMinVelocity;
        [FieldOffset(8)] public ResourcePointer specialJump;
        [FieldOffset(16)] public int specialJumpPause;
        [FieldOffset(20)][EnumRef(typeof(Enums.EUseJump))] public int useJump;
    }
    
    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PitchParameters
    {
        [FieldOffset(4)] public float maxPitch;
        [FieldOffset(8)] public int minStepDeltaT;
        [FieldOffset(12)] public int minStepDeltaTMainAvatar;
        [FieldOffset(16)] public float minTurnRadius;
        [FieldOffset(20)] public float minVelocity;
        [FieldOffset(24)] public float minVelocityPitch;
        [FieldOffset(28)] public float pitchMaxVelocity;
        [FieldOffset(32)] public float topVelocity;
        [FieldOffset(36)] public float topVelocityPitch;
    }
    
    [StructSize(68)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ReinsSettings
    {
        [FieldOffset(4)] public ResourcePointer disablingAnimations;
        [FieldOffset(12)] public string handBone;
        [FieldOffset(24)] public string handBone01;
        [FieldOffset(36)][EnumRef(typeof(Enums.ETroopMember))] public int member;
        [FieldOffset(40)] public string reinsBone;
        [FieldOffset(52)] public string reinsBone01;
        [FieldOffset(64)] public bool use;
    }
}
