// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(148)]
[XdbName("gameMechanics.world.ship.VisualShip")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualShip
{
    [FieldOffset(24)]
    [EnumRef(typeof(Enums.CannonVisualType))]
    public int cannonVisualType;

    [FieldOffset(28)] public ResourcePointer[] compatibleSkins;
    [FieldOffset(44)] public TextFileRef description;
    [FieldOffset(60)] public ResourcePointer image;
    [FieldOffset(68)] public TextFileRef name;
    [FieldOffset(84)] public NullablePointer[] parts;
    [FieldOffset(100)] public float radius;
    [FieldOffset(104)] public Slot[] slots;
    [FieldOffset(120)] public int sourceFileCRC;
    [FieldOffset(124)] public ResourcePointer steeringParams;
    [FieldOffset(132)] public ResourcePointer transportVisObject;
    [FieldOffset(140)] public ResourcePointer unlock;

    [StructSize(88)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Slot
    {
        [FieldOffset(4)] public ResourcePointer[] allowedDeviceTypes;
        [FieldOffset(20)] public Vector3 coord;
        [FieldOffset(32)] public NullablePointer interfaceData;

        [FieldOffset(36)]
        [EnumRef(typeof(Enums.SlotName))]
        public int name;

        [FieldOffset(40)] public float pitch;
        [FieldOffset(44)] public float pitchRange;
        [FieldOffset(48)] public float roll;
        [FieldOffset(52)] public Quaternion rotation;
        [FieldOffset(68)] public float scale;

        [FieldOffset(72)]
        [EnumRef(typeof(Enums.ShipSide))]
        public int side;

        [FieldOffset(76)] public float yaw;
        [FieldOffset(80)] public float yawRange;
        [FieldOffset(84)] public bool canBeEmpty;
        [FieldOffset(85)] public bool isLootSlot;
    }
}
