// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(168)]
[XdbName("WeaponHoldingRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WeaponHoldingRoot
{
    [FieldOffset(24)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponAny;

    [FieldOffset(40)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponBoast;

    [FieldOffset(56)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponByState;

    [FieldOffset(72)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponCast;

    [FieldOffset(88)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponChargedWand;

    [FieldOffset(104)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponMelee;

    [FieldOffset(120)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponNone;

    [FieldOffset(136)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponRanged;

    [FieldOffset(152)]
    [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
    public int[] weaponWand;
}
