// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76;

[StructSize(128)]
[XdbName("gameMechanics.map.zone.ZoneResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ZoneResource
{
    [FieldOffset(24)] public string[] attributes;
    [FieldOffset(40)] public int color;
    [FieldOffset(44)] public TextFileRef description;
    [FieldOffset(60)] public string internalName;
    [FieldOffset(72)] public TextFileRef name;
    [FieldOffset(88)] public ResourcePointer zoneLights;
    [FieldOffset(96)] public bool useColdBreath;
    [FieldOffset(108)] public ResourcePointer parentZone;
    [FieldOffset(116)] public ResourcePointer pvpType;
}
