// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum ActionType
{
    Simple = 0,
    Music = 1,
    AmbientOutdoor = 2,
    AmbientIndoor = 3,
    MusicSource = 4,
    GlobalParams = 5,
}
