// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum SpellResistType
{
    SRT_BuffDebuff = 0,
    SRT_DoT = 1,
    SRT_HoT = 2,
    SRT_CC = 3,
    SRT_None = 4,
    SRT_CCdurationless = 5,
}
