// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum UIOptionViewType
{
    UI_OPTION_VIEW_LABEL = 0,
    UI_OPTION_VIEW_CHECKBOX = 1,
    UI_OPTION_VIEW_RADIO = 2,
    UI_OPTION_VIEW_SLIDER = 3,
    UI_OPTION_VIEW_LIST = 4,
    UI_OPTION_VIEW_PUSH_BUTTON = 5,
}
