// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum VertexElementType
{
    FLOAT1 = 1,
    FLOAT2 = 2,
    FLOAT3 = 3,
    FLOAT4 = 4,
    SHORT2 = 5,
    SHORT4 = 6,
    COLOR4 = 7,
    UBYTE4 = 8,
    USH0RT2 = 9,
    USH0RT4 = 10,
    HALF4 = 11,
    UNUSED = 12,
}
