// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum ViewType
{
    CLIENT_DATA_PARAM_DEFAULT = 0,
    CLIENT_DATA_DRESS_SLOT = 1,
    CLIENT_DATA_PARAM_MONEY = 2,
    CLIENT_DATA_PLAYER_NAME = 3,
}
