// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum BattleJoinPolicy
{
    SimpleJoin = 0,
    SoloDepartOnly = 1,
    PremadeLeaderJoinOnly = 2,
    PremadeLeaderDepartOnly = 3,
    PremadeLeaderJoinOrDepart = 4,
    PremadeHearthstoneDepart = 5,
}
