// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum EAutoHasten
{
    AUTOHASTEN_NONE = 0,
    AUTOHASTEN_FIRSTKEY = 1,
    AUTOHASTEN_FULLPLAYBACK = 2,
}
