// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum GuildMemberRight
{
    GMRChat = 0,
    GMROfficerChat = 1,
    GMRRecruit = 2,
    GMRPromoteDemote = 3,
    GMRKick = 4,
    GMRWearSymobolics = 5,
    GMRModifySymbolics = 6,
    GMRModifyMessage = 7,
    GMRModifyDescription = 8,
    GMRModifyMemberDescription = 9,
    GMRPutMoney = 10,
    GMRGetMoney = 11,
    GMRDue = 12,
    GMRMWarCommander = 13,
    GMRApplyTalents = 14,
    GMRForgetTalents = 15,
    GMRDistributeTabards = 16,
    GMRCreateClanHall = 17,
    GMRApplyHallAndBossTalents = 18,
    GMRChangeBossAbilities = 19,
    GMRChangeBeastiary = 20,
}
