// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum OrientationMode
{
    COMMON = 0,
    WORLD_X = 1,
    WORLD_Y = 2,
    WORLD_Z = 3,
    X_AXIS = 4,
    Y_AXIS = 5,
    Z_AXIS = 6,
    BILLBOARD = 7,
}
