// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum QualityEnum
{
    QUALITY_SYSTEM = 0,
    QUALITY_JUNK = 1,
    QUALITY_GOODS = 2,
    QUALITY_COMMON = 3,
    QUALITY_UNCOMMON = 4,
    QUALITY_RARE = 5,
    QUALITY_EPIC = 6,
    QUALITY_LEGENDARY = 7,
    QUALITY_RELIC = 8,
    QUALITY_DRAGON = 9,
}
