// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum TextureElementType
{
    DXT1,
    DXT3,
    DXT5,
    RGBA,
    L8,
    D24,
    D16,
    C565,
    C4444,
    RG16,
    R32F,
    RGBA16,
    D24S8,
    A8L8,
    RGBA_VOLUME,
    R10G10B10A2
}
