// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum AffectGroup
{
    All = 0,
    Group = 1,
    Raid = 2,
    Friends = 3,
    Enemies = 4,
}
