// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum EHoldWeapon
{
    WEAPON_DEFAULT = 0,
    WEAPON_NONE = 1,
    WEAPON_MELEE = 2,
    WEAPON_RANGED = 3,
}
