// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum EItemPriority
{
    DEFAULT = 0,
    RITUAL = 1,
    GUILD = 2,
    CUSTOM = 3,
    PREVIEW = 4,
    HIDE_ALL = 5,
}
