// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V3_0_00_89.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum GuildMemberRight
{
    GMRChat = 0,
    GMROfficerChat = 1,
    GMRRecruit = 2,
    GMRPromoteDemote = 3,
    GMRKick = 4,
    GMRWearSymobolics = 5,
    GMRModifySymbolics = 6,
    GMRModifyMessage = 7,
    GMRModifyDescription = 8,
    GMRModifyMemberDescription = 9,
}
