// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(68)]
[XdbName("AnimationFromParentComponent")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AnimationFromParentComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public bool synchronizeAnimationPosition;
    [FieldOffset(40)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int ifAnimationNotExistsRun;
    [FieldOffset(44)] public ResourcePointer controller;
    [FieldOffset(52)] public AnimationsReplacement[] animationsReplacements;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AnimationsReplacement
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int play;
        [FieldOffset(8)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int[] forAnimations;
    }
}
