// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(76)]
[XdbName("AnimatedParameters")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AnimatedParameters
{
    [FieldOffset(24)] public float fps;
    [FieldOffset(28)] public Vector3[] diffuseMul;
    [FieldOffset(44)] public Vector3[] diffuseAdd;
    [FieldOffset(60)] public Vector3[] cameraTranslate;
}
