// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(68)]
[XdbName("CameraTrackAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CameraTrackAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public TargetPoint[] targetPoints;
    [FieldOffset(52)] public TargetPoint[] cameraPoints;

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TargetPoint
    {
        [FieldOffset(4)] public Vector3 position;
        [FieldOffset(16)] public float duration;
    }
}
