// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(64)]
[XdbName("CommonMaterialParams")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CommonMaterialParams
{
    [FieldOffset(24)] public bool vertexBakedLight;
    [FieldOffset(25)] public bool useMaskColor;
    [FieldOffset(28)] public int specularColorModifier;
    [FieldOffset(32)] public bool selfillum;
    [FieldOffset(36)] public ResourcePointer envSpecularTexture;
    [FieldOffset(44)] public ResourcePointer envReflectionTexture;
    [FieldOffset(52)] public ResourcePointer effectMaskTexture;
    [FieldOffset(60)] public int contourColorModifier;
}
