// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(40)]
[XdbName("gameMechanics.constructor.schemes.item.ContainerShape")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ContainerShape
{
    [FieldOffset(24)] public Pocket[] pockets;

    [StructSize(48)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Pocket
    {
        [FieldOffset(4)] public TextFileRef name;
        [FieldOffset(20)] public ResourcePointer image;
        [FieldOffset(28)] public TextFileRef description;
        [FieldOffset(44)] public NullablePointer condition;
    }
}
