// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(56)]
[XdbName("CreatureChargedSpellAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureChargedSpellAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public int fadeOutTime;
    [FieldOffset(40)] public int fadeInTime;
    [FieldOffset(44)][EnumRef(typeof(Enums.FxLocators))] public int effectLocator;
    [FieldOffset(48)] public ResourcePointer effectFx;
}
