// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(40)]
[XdbName("gameMechanics.world.ship.elements.DevicePack")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DevicePack
{
    [FieldOffset(24)] public SoldDevice[] soldDevices;

    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SoldDevice
    {
        [FieldOffset(4)] public ResourcePointer device;
        [FieldOffset(12)] public ResourcePointer currency;
        [FieldOffset(24)] public long amount;
    }
}
