// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(60)]
[XdbName("DeviceVisActionChangeModel")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DeviceVisActionChangeModel
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(40)] public ResourcePointer visObj;
    [FieldOffset(48)] public float priority;
    [FieldOffset(52)] public ResourcePointer collision;
}
