// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(40)]
[XdbName("EffectsList")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class EffectsList
{
    [FieldOffset(24)] public Effect[] effects;

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Effect
    {
        [FieldOffset(4)] public int rate;
        [FieldOffset(8)][EnumRef(typeof(Enums.ETroopMember))] public int member;
        [FieldOffset(12)] public string locatorName;
        [FieldOffset(24)][EnumRef(typeof(Enums.FxLocators))] public int locator;
        [FieldOffset(28)] public bool fixPoint;
        [FieldOffset(32)] public int fadeOutTime;
        [FieldOffset(36)] public int fadeInTime;
        [FieldOffset(40)] public ResourcePointer effect;
        [FieldOffset(48)] public int adddedDelay;
    }
}
