// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(40)]
[XdbName("gameMechanics.world.gameRoot.FamilyRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class FamilyRoot
{
    [FieldOffset(24)] public Spell[] spells;
    
    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Spell
    {
        [FieldOffset(4)] public ResourcePointer spell;
        [FieldOffset(12)] public int[] experienceTable;
    }
}
