// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(448)]
[XdbName("GMUIHelper")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GMUIHelper
{
    [FieldOffset(24)] public float warningLowStatPercent;
    [FieldOffset(28)] public ResourcePointer variablesAliases;
    [FieldOffset(36)] public UnlocksSpecial unlocksSpecial;
    [FieldOffset(64)] public ResourcePointer socialNetwork;
    [FieldOffset(72)] public ResourcePointer slashCommands;
    [FieldOffset(80)] public ResourcePointer ruleNews;
    [FieldOffset(88)] public ResourcePointer referralContentKey;
    [FieldOffset(96)] public ResourcePointer notifications;
    [FieldOffset(104)] public ResourcePointer leagueFaction;
    [FieldOffset(112)] public ResourcePointer itemMall;
    [FieldOffset(120)] public ResourcePointer interfaceMaps;
    [FieldOffset(128)] public ImpactProducerUIInfos impactProducerUIInfos;
    [FieldOffset(196)] public TextFileRef gameItemCompositNameSpace;
    [FieldOffset(212)] public EquipmentData equipmentData;
    [FieldOffset(236)] public ResourcePointer empireFaction;
    [FieldOffset(244)] public ResourcePointer[] detectors;
    [FieldOffset(260)] public DeniedTag[] deniedTags;
    [FieldOffset(276)] public ResourcePointer[] currencies;
    [FieldOffset(292)] public ResourcePointer contextActions;
    [FieldOffset(300)] public ResourcePointer conditionEvents;
    [FieldOffset(312)] public ClassSpecificData classSpecificData;
    [FieldOffset(332)] public TextFileRef chestOpening;
    [FieldOffset(348)] public AuctionFilter auctionFilter;
    [FieldOffset(400)] public ResourcePointer antiSpam;
    [FieldOffset(408)] public ResourcePointer antiFlood;
    [FieldOffset(416)] public DeniedTag[] allowedTags;
    [FieldOffset(432)] public AbilitiesAliase[] abilitiesAliases;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class UnlocksSpecial
    {
        [FieldOffset(4)] public ResourcePointer[] promotionUnlocks;
        [FieldOffset(20)] public ResourcePointer greatnessUnlock;
    }

    [StructSize(68)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ImpactProducerUIInfos
    {
        [FieldOffset(4)] public ResourcePointer spell;
        [FieldOffset(12)] public ResourcePointer other;
        [FieldOffset(20)] public ResourcePointer mapModifier;
        [FieldOffset(28)] public ResourcePointer exploit;
        [FieldOffset(36)] public ResourcePointer buff;
        [FieldOffset(44)] public ResourcePointer barrier;
        [FieldOffset(52)] public ResourcePointer attack;
        [FieldOffset(60)] public ResourcePointer ability;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class EquipmentData
    {
        [FieldOffset(4)]
        [EnumRef(typeof(Enums.DressSlot))]
        public int[] slots;

        [FieldOffset(20)] public int presetsCount;
    }

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DeniedTag
    {
        [FieldOffset(4)] public string[] tags;
        [FieldOffset(20)] public ResourcePointer contentKey;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ClassSpecificData
    {
        [FieldOffset(0)] public Stalker stalker;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Stalker
        {
            [FieldOffset(4)] public Arrow[] arrows;

            [StructSize(32)]
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class Arrow
            {
                [FieldOffset(4)] public ResourcePointer shotSpell;
                [FieldOffset(12)] public ResourcePointer enchatSpell;
                [FieldOffset(20)] public string alias;
            }
        }
    }

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AuctionFilter
    {
        [FieldOffset(4)] public ItemQualitie[] itemQualities;
        [FieldOffset(20)] public ItemQualitie[] itemClasses;
        [FieldOffset(36)] public ResourcePointer defaultItemQuality;
        [FieldOffset(44)] public ResourcePointer defaultItemClass;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ItemQualitie
        {
            [FieldOffset(4)] public ResourcePointer item;
            [FieldOffset(12)] public string alias;
        }
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AbilitiesAliase
    {
        [FieldOffset(4)] public string alias;
        [FieldOffset(16)] public ResourcePointer ability;
    }
}
