// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(40)]
[XdbName("ItemMallCurrencyDescriptions")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ItemMallCurrencyDescriptions
{
    [FieldOffset(24)] public Currencie[] currencies;

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Currencie
    {
        [FieldOffset(4)] public TextFileRef name;
        [FieldOffset(20)] public ResourcePointer image;

        [FieldOffset(28)]
        [EnumRef(typeof(Enums.ItemMallCurrency))]
        public int currencyId;

        [FieldOffset(32)] public ResourcePointer contentKey;
        [FieldOffset(40)] public bool bindWarning;
    }
}
