// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(88)]
[XdbName("LightComponent")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class LightComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public float radius;
    [FieldOffset(40)] public Vector3 pivot;
    [FieldOffset(52)] public float intensityRandom;
    [FieldOffset(56)] public float intensity;
    [FieldOffset(60)] public float facingValue;
    [FieldOffset(64)] public ResourcePointer editorVisObj;
    [FieldOffset(72)] public Vector3 direction;
    [FieldOffset(84)] public float attenuationPower;
}
