// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(48)]
[XdbName("itemService.elements.loginLottery.LoginLotteryResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class LoginLotteryResource
{
    [FieldOffset(24)] public Prize[] prizes;
    [FieldOffset(40)] public ResourcePointer comboCounter;
    
    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Prize
    {
        [FieldOffset(4)] public bool repetative;
        [FieldOffset(8)] public PrizeItem[] prizes;
        [FieldOffset(24)] public int daysToReceive;
        [FieldOffset(28)] public ResourcePointer counter;
        
        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class PrizeItem
        {
            [FieldOffset(4)] public int stackCount;
            [FieldOffset(8)] public ResourcePointer item;
            [FieldOffset(16)] public bool bound;
        }
    }
}
