// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(48)]
[XdbName("gameMechanics.elements.resources.ResourceDressItem")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ResourceDressItem
{
    [FieldOffset(24)] public bool hideText;
    [FieldOffset(36)][EnumRef(typeof(Enums.DressSlot))] public int slot;
    [FieldOffset(40)] public bool secondary;
    [FieldOffset(44)] public int count;
}
