// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(184)]
[XdbName("gameMechanics.world.gameRoot.ShipRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ShipRoot
{
    [FieldOffset(24)] public ResourcePointer unsummonShipSpell;
    [FieldOffset(32)] public ResourcePointer switchShipSkinSpell;
    [FieldOffset(40)] public ResourcePointer switchShipHullSpell;
    [FieldOffset(48)] public ResourcePointer summonShipSpell;
    [FieldOffset(56)] public ResourcePointer startRepairSpell;
    [FieldOffset(64)] public ResourcePointer showShipInProgressSpell;
    [FieldOffset(72)] public ResourcePointer shipNameGeneratingInfo;
    [FieldOffset(80)] public RunWaveInfo[] runWaveInfo;
    [FieldOffset(96)] public ResourcePointer replaceDevicesSpell;
    [FieldOffset(104)] public float repairTickResourceUsage;
    [FieldOffset(108)] public float repairTickPercent;
    [FieldOffset(112)] public ResourcePointer getShipRepairProgressSpell;
    [FieldOffset(120)] public ResourcePointer getShipProgressSpell;
    [FieldOffset(128)] public ResourcePointer finishShipConstructionSpell;
    [FieldOffset(136)] public ResourcePointer finishDevicesReplacementSpell;
    [FieldOffset(144)] public DefaultRunWave defaultRunWave;
    [FieldOffset(176)] public ResourcePointer astrolabeSpell;
    
    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RunWaveInfo
    {
        [FieldOffset(4)] public ResourcePointer[] zoneLights;
        [FieldOffset(20)] public RunWave runWave;
        
        [StructSize(32)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class RunWave
        {
            [FieldOffset(4)] public ResourcePointer visObject;
            [FieldOffset(12)] public float speedStart;
            [FieldOffset(16)] public float speedEnd;
            [FieldOffset(20)] public float scale;
            [FieldOffset(24)] public float runWaveRadius;
            [FieldOffset(28)] public float elastic;
        }
    }
    
    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DefaultRunWave
    {
        [FieldOffset(4)] public ResourcePointer visObject;
        [FieldOffset(12)] public float speedStart;
        [FieldOffset(16)] public float speedEnd;
        [FieldOffset(20)] public float scale;
        [FieldOffset(24)] public float runWaveRadius;
        [FieldOffset(28)] public float elastic;
    }
}
