// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(40)]
[XdbName("ShipBuildStatusResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ShipBuildStatusResource
{
    [FieldOffset(24)] public Stage[] stages;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Stage
    {
        [FieldOffset(4)] public float percent;
        [FieldOffset(8)][XdbName("object")] public ResourcePointer @object;
    }
}
