// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(540)]
[XdbName("SlonRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SlonRoot
{
    [FieldOffset(24)] public ResourcePointer waterFootstepMaterial;
    [FieldOffset(32)] public WaterCkloakModifiers waterCkloakModifiers;
    [FieldOffset(48)] public ResourcePointer wallFX;
    [FieldOffset(56)] public ResourcePointer wallCollision;
    [FieldOffset(64)] public ResourcePointer visualSettings;
    [FieldOffset(72)] public ResourcePointer visCharTemplates;
    [FieldOffset(80)] public ResourcePointer underWaterRays;
    [FieldOffset(88)] public ResourcePointer unarmedWeaponItemClass;
    [FieldOffset(96)] public ResourcePointer textFiles;
    [FieldOffset(104)] public int spellResistFxForestall;
    [FieldOffset(108)] public ResourcePointer spellResistFx;
    [FieldOffset(116)] public ResourcePointer soundRoot;
    [FieldOffset(124)] public ResourcePointer shipCollisionFX;
    [FieldOffset(132)] public ResourcePointer shadowTexture;
    [FieldOffset(140)] public ResourcePointer rightArmController;
    [FieldOffset(148)] public ResourcePointer propertiesOfCreatureAnimations;
    [FieldOffset(156)] public ResourcePointer projectileVisObj;
    [FieldOffset(164)] public ResourcePointer priorityOrders;
    [FieldOffset(172)] public PortraitManagerLight portraitManagerLight;
    [FieldOffset(292)] public ResourcePointer parrySounds;
    [FieldOffset(300)] public NullablePointer newWeaponDressed;
    [FieldOffset(304)] public ResourcePointer musicSettings;
    [FieldOffset(312)] public ResourcePointer mobVisualScript;
    [FieldOffset(320)] public float minSelectionBox;
    [FieldOffset(324)] public NullablePointer lootStartAction;
    [FieldOffset(328)] public NullablePointer lootEndAction;
    [FieldOffset(332)] public ResourcePointer levelChangedScript;
    [FieldOffset(340)] public ResourcePointer leftArmController;
    [FieldOffset(348)] public ResourcePointer haloTable;
    [FieldOffset(356)] public ResourcePointer guildRoot;
    [FieldOffset(364)] public Fatalitie[] fatalities;
    [FieldOffset(380)] public ResourcePointer fairyLevelChangedScript;
    [FieldOffset(388)] public ResourcePointer deviceVisObj;
    [FieldOffset(396)] public ResourcePointer defaultGuildVisualSettings;
    [FieldOffset(404)] public ResourcePointer creatureVisualScript;
    [FieldOffset(412)] public ResourcePointer creatureVisObj;
    [FieldOffset(420)] public ResourcePointer constants;
    [FieldOffset(428)] public ResourcePointer coldBreathFx;
    [FieldOffset(436)] public ResourcePointer cloakDefaultLODs;
    [FieldOffset(444)] public Cameras cameras;
    [FieldOffset(480)] public int blockParryFxForestall;
    [FieldOffset(484)] public ResourcePointer blockParryFx;
    [FieldOffset(492)] public ResourcePointer avatarVisualScript;
    [FieldOffset(500)] public ResourcePointer avatarVisObj;
    [FieldOffset(508)] public ResourcePointer astralTransitionFogStart;
    [FieldOffset(516)] public ResourcePointer astralTransitionFogEnd;
    [FieldOffset(524)] public ResourcePointer astralTransitionFog;
    [FieldOffset(532)] public ResourcePointer abordageBubbleTemplate;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class WaterCkloakModifiers
    {
        [FieldOffset(4)] public float theGe;
        [FieldOffset(8)] public float shapeFixityCoeff;
        [FieldOffset(12)] public float airFrictionCoeff;
    }

    [StructSize(120)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PortraitManagerLight
    {
        [FieldOffset(4)] public float desaturation;
        [FieldOffset(8)] public ResourcePointer animatedSelfIllumColor;
        [FieldOffset(16)] public ResourcePointer animatedPointLightColor;
        [FieldOffset(24)] public ResourcePointer animatedDiffuseColor;
        [FieldOffset(32)] public ResourcePointer animatedAmbientColor;

        [FieldOffset(40)]
        [XdbName("WaterGradientStart")]
        public int waterGradientStart;

        [FieldOffset(44)]
        [XdbName("WaterGradientEnd")]
        public int waterGradientEnd;

        [FieldOffset(48)]
        [XdbName("TerrainSpecularColor")]
        public int terrainSpecularColor;

        [FieldOffset(52)]
        [XdbName("TerrainContourPower")]
        public float terrainContourPower;

        [FieldOffset(56)]
        [XdbName("TerrainContourColor")]
        public int terrainContourColor;

        [FieldOffset(60)]
        [XdbName("SunLightYaw")]
        public float sunLightYaw;

        [FieldOffset(64)]
        [XdbName("SunLightPitch")]
        public float sunLightPitch;

        [FieldOffset(68)]
        [XdbName("SpecularWaterColor")]
        public int specularWaterColor;

        [FieldOffset(72)]
        [XdbName("SpecularColor")]
        public int specularColor;

        [FieldOffset(76)]
        [XdbName("SelfIllumColor")]
        public int selfIllumColor;

        [FieldOffset(80)]
        [XdbName("PointLightColor")]
        public int pointLightColor;

        [FieldOffset(84)]
        [XdbName("FogStart")]
        public float fogStart;

        [FieldOffset(88)][XdbName("FogEnd")] public float fogEnd;

        [FieldOffset(92)]
        [XdbName("FogColor")]
        public int fogColor;

        [FieldOffset(96)]
        [XdbName("FadeStart")]
        public float fadeStart;

        [FieldOffset(100)]
        [XdbName("FadeEnd")]
        public float fadeEnd;

        [FieldOffset(104)]
        [XdbName("DiffuseColor")]
        public int diffuseColor;

        [FieldOffset(108)]
        [XdbName("ContourColor")]
        public int contourColor;

        [FieldOffset(112)]
        [XdbName("AmbientFactor")]
        public float ambientFactor;

        [FieldOffset(116)]
        [XdbName("AmbientColor")]
        public int ambientColor;
    }

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Fatalitie
    {
        [FieldOffset(4)]
        [EnumRef(typeof(Enums.FatalityType))]
        public int type;

        [FieldOffset(8)] public NullablePointer offenderDeathScript;
        [FieldOffset(12)] public NullablePointer casterFxScript;
    }

    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Cameras
    {
        [FieldOffset(4)] public ResourcePointer shipZoom;
        [FieldOffset(12)] public ResourcePointer player;
        [FieldOffset(20)] public ResourcePointer navigator;
        [FieldOffset(28)] public ResourcePointer deviceZoom;
    }
}
