// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(56)]
[XdbName("SocialNetwork")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SocialNetwork
{
    [FieldOffset(24)] public RepostBonusUnlock[] repostBonusUnlocks;
    [FieldOffset(40)] public AutoPostResourceText[] autoPostResourceTexts;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RepostBonusUnlock
    {
        [FieldOffset(4)] public int repostId;
        [FieldOffset(8)] public ResourcePointer bonusUnlock;
    }

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AutoPostResourceText
    {
        [FieldOffset(4)] public ResourcePointer resource;
        [FieldOffset(12)] public AdaptedText[] adaptedTexts;

        [StructSize(28)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class AdaptedText
        {
            [FieldOffset(4)] public ResourcePointer textMessageLimit;
            [FieldOffset(12)] public TextFileRef text;
        }
    }
}
