// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(92)]
[XdbName("Sound2DAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Sound2DAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public Sound sound;
    [FieldOffset(60)] public bool resetGlobalParamsOnStop;
    [FieldOffset(64)] public MusicSourceParameter[] musicSourceParameters;
    [FieldOffset(80)] public float musicSourceMaxRadius;
    [FieldOffset(84)] public bool forcedSoundStop;

    [FieldOffset(88)]
    [EnumRef(typeof(Enums.ActionType))]
    public int actionType;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class MusicSourceParameter
    {
        [FieldOffset(4)] public float value;
        [FieldOffset(8)] public ResourcePointer parameter;
    }
}
