// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(72)]
[XdbName("gameMechanics.world.worldDrop.SuffixNamer")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SuffixNamer
{
    [FieldOffset(24)] public TextFileRef[] prefixes;

    [FieldOffset(40)]
    [EnumRef(typeof(Enums.NamePart))]
    public int[] name;

    [FieldOffset(56)] public Item[] items;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Item
    {
        [FieldOffset(4)] public QualityPrefixe[] qualityPrefixes;
        [FieldOffset(20)] public ResourcePointer baseItem;

        [StructSize(28)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class QualityPrefixe
        {
            [FieldOffset(4)] public ResourcePointer quality;
            [FieldOffset(12)] public TextFileRef prefix;
        }
    }
}
