// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(48)]
[XdbName("gameMechanics.constructor.schemes.talent.TalentAbility")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TalentAbility
{
    [FieldOffset(20)] public ResourcePointer unlock;
    [FieldOffset(28)] public NullablePointer parentTalent;
    [FieldOffset(32)] public bool isRecommended;
    [FieldOffset(40)] public ResourcePointer ability;
}
