// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(44)]
[XdbName("VisMobModifierPet")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisMobModifierPet
{
    [FieldOffset(28)] public Level[] levels;

    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Level
    {
        [FieldOffset(4)] public ResourcePointer visualMob;
        [FieldOffset(12)] public int startLevel;
        [FieldOffset(16)] public NullablePointer playAfterChanging;
        [FieldOffset(20)] public FaceVariation[] faceVariations;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class FaceVariation
        {
            [FieldOffset(4)] public ResourcePointer level;
            [FieldOffset(12)][XdbName("base")] public ResourcePointer @base;
        }
    }
}
