// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(72)]
[XdbName("VisualMount")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualMount
{
    [FieldOffset(24)] public ResourcePointer visualMountClass;
    [FieldOffset(32)] public Scale[] scales;
    [FieldOffset(48)] public float mountSize;
    [FieldOffset(52)] public ResourcePointer mount;
    [FieldOffset(60)] public CameraShift cameraShift;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Scale
    {
        [FieldOffset(4)] public float mountScale;
        [FieldOffset(8)] public ResourcePointer character;
    }

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CameraShift
    {
        [FieldOffset(4)] public float additionalShift;
        [FieldOffset(8)] public float absoluteHeight;
    }
}
