// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(176)]
[XdbName("WebRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WebRoot
{
    [FieldOffset(24)] public ResourcePointer webCommonRegistry;
    [FieldOffset(32)] public ResourcePointer socialPostContentsRegistry;
    [FieldOffset(40)] public ResourcePointer socialNetworksRegistry;
    [FieldOffset(48)] public TextFileRef repostInfoLink;
    [FieldOffset(64)] public ResourcePointer namedWebResourcesRegistry;
    [FieldOffset(72)] public ImageBrowserScript imageBrowserScript;
    [FieldOffset(112)] public ImageBrowserScript dataReceiverScript;
    [FieldOffset(152)] public WString contentKey;
    [FieldOffset(164)] public string acceptLanguage;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ImageBrowserScript
    {
        [FieldOffset(4)] public FileRef main;
        [FieldOffset(24)] public FileRef[] dependencies;
    }
}
