// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(364)]
[XdbName("WidgetTextView")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WidgetTextView
{
    [FieldOffset(24)] public ResourcePointer textureMask;
    [FieldOffset(32)] public ResourcePointer soundShow;
    [FieldOffset(40)] public ResourcePointer soundHide;
    [FieldOffset(48)] public string reactionWheelUp;
    [FieldOffset(60)] public string reactionWheelDown;
    [FieldOffset(72)] public string reactionOnPointing;
    [FieldOffset(84)] public ResourcePointer pickMask;
    [FieldOffset(92)] public bool isProtected;
    [FieldOffset(93)] public bool forceWheel;
    [FieldOffset(96)] public string forceReactionOnPointing;
    [FieldOffset(108)] public float fade;
    [FieldOffset(112)] public bool clipContent;
    [FieldOffset(116)] public BindSection[] bindSections;
    [FieldOffset(132)][XdbName("Visible")] public bool visible;
    [FieldOffset(133)][XdbName("TransparentInput")] public bool transparentInput;
    [FieldOffset(136)][XdbName("TabOrder")] public int tabOrder;
    [FieldOffset(140)][XdbName("Priority")] public int priority;
    [FieldOffset(144)][XdbName("Placement")] public Placement placement;
    [FieldOffset(224)][XdbName("PickChildrenOnly")] public bool pickChildrenOnly;
    [FieldOffset(228)][XdbName("Name")] public string name;
    [FieldOffset(240)][XdbName("IgnoreDblClick")] public bool ignoreDblClick;
    [FieldOffset(244)][XdbName("FrontLayer")] public ResourcePointer frontLayer;
    [FieldOffset(252)][XdbName("Enabled")] public bool enabled;
    [FieldOffset(256)][XdbName("Children")] public ResourcePointer[] children;
    [FieldOffset(272)][XdbName("BackLayer")] public ResourcePointer backLayer;
    [FieldOffset(284)] public bool pickObjectsOnly;
    [FieldOffset(288)] public float minWidth;
    [FieldOffset(292)] public float maxWidth;
    [FieldOffset(296)][XdbName("TextValues")] public TextValue[] textValues;
    [FieldOffset(312)][XdbName("TextStyle")] public TextStyle textStyle;
    [FieldOffset(336)][XdbName("FormatFileRef")] public TextFileRef formatFileRef;
    [FieldOffset(352)][XdbName("DefaultTag")] public WString defaultTag;
    
    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class BindSection
    {
        [FieldOffset(4)] public string[] bindedReactions;
        [FieldOffset(20)] public string bindSection;
    }
    
    [StructSize(80)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Placement
    {
        [FieldOffset(4)] public ResourcePointer[] sizingWidgets;
        [FieldOffset(20)] public ResourcePointer sizingWidget;
        [FieldOffset(28)][XdbName("Y")] public Y y;
        [FieldOffset(52)][XdbName("X")] public Y x;
        [FieldOffset(76)][XdbName("QuantumScale")] public bool quantumScale;
        
        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Y
        {
            [FieldOffset(4)][XdbName("Sizing")][EnumRef(typeof(Enums.WidgetSizing))] public int sizing;
            [FieldOffset(8)][XdbName("Size")] public float size;
            [FieldOffset(12)][XdbName("Pos")] public float pos;
            [FieldOffset(16)][XdbName("HighPos")] public float highPos;
            [FieldOffset(20)][XdbName("Align")][EnumRef(typeof(Enums.WidgetAlign))] public int align;
        }
    }
    
    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextValue
    {
        [FieldOffset(4)][XdbName("TagValueFileRef")] public TextFileRef tagValueFileRef;
        [FieldOffset(20)][XdbName("Tag")] public WString tag;
    }
    
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextStyle
    {
        [FieldOffset(4)] public bool wrapText;
        [FieldOffset(5)] public bool showClippedSymbol;
        [FieldOffset(6)] public bool showClippedLine;
        [FieldOffset(7)] public bool multiline;
        [FieldOffset(8)] public float lineSpacing;
        [FieldOffset(12)] public bool ellipsis;
        [FieldOffset(16)][EnumRef(typeof(Enums.BlendEffectType))] public int blendEffect;
        [FieldOffset(20)][XdbName("Align")][EnumRef(typeof(Enums.AlignY))] public int align;
    }
}
