// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V4_0_02_43;

[StructSize(224)]
[XdbName("ZoneLights")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ZoneLights
{
    [FieldOffset(24)] public float waterReflectionCoefficient;
    [FieldOffset(28)] public ResourcePointer waterLight;
    [FieldOffset(36)] public RandomLight[] randomLights;
    [FieldOffset(52)] public InstantLight[] instantLights;
    [FieldOffset(68)] public int index;
    [FieldOffset(72)] public InstantLight defaultLight;

    [StructSize(196)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RandomLight
    {
        [FieldOffset(4)] public ResourcePointer weatherType;
        [FieldOffset(12)] public float probability;
        [FieldOffset(16)] public float minStartTime;
        [FieldOffset(20)] public float minDuration;
        [FieldOffset(24)] public float maxStartTime;
        [FieldOffset(28)] public float maxDuration;
        [FieldOffset(32)] public InstantLight light;
        [FieldOffset(184)] public float fadeOutSeconds;
        [FieldOffset(188)] public float fadeInSeconds;
        [FieldOffset(192)][EnumRef(typeof(Enums.ESoundImpact))] public int ambientSoundImpact;
    }

    [StructSize(152)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class InstantLight
    {
        [FieldOffset(4)] public float time;
        [FieldOffset(8)] public ResourcePointer skyMesh;
        [FieldOffset(16)] public ResourcePointer postEffectParams;
        [FieldOffset(24)] public Light light;
        [FieldOffset(144)] public ResourcePointer areaEffect;

        [StructSize(120)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Light
        {
            [FieldOffset(4)] public float desaturation;
            [FieldOffset(8)] public ResourcePointer animatedSelfIllumColor;
            [FieldOffset(16)] public ResourcePointer animatedPointLightColor;
            [FieldOffset(24)] public ResourcePointer animatedDiffuseColor;
            [FieldOffset(32)] public ResourcePointer animatedAmbientColor;
            [FieldOffset(40)][XdbName("WaterGradientStart")] public int waterGradientStart;
            [FieldOffset(44)][XdbName("WaterGradientEnd")] public int waterGradientEnd;
            [FieldOffset(48)][XdbName("TerrainSpecularColor")] public int terrainSpecularColor;
            [FieldOffset(52)][XdbName("TerrainContourPower")] public float terrainContourPower;
            [FieldOffset(56)][XdbName("TerrainContourColor")] public int terrainContourColor;
            [FieldOffset(60)][XdbName("SunLightYaw")] public float sunLightYaw;
            [FieldOffset(64)][XdbName("SunLightPitch")] public float sunLightPitch;
            [FieldOffset(68)][XdbName("SpecularWaterColor")] public int specularWaterColor;
            [FieldOffset(72)][XdbName("SpecularColor")] public int specularColor;
            [FieldOffset(76)][XdbName("SelfIllumColor")] public int selfIllumColor;
            [FieldOffset(80)][XdbName("PointLightColor")] public int pointLightColor;
            [FieldOffset(84)][XdbName("FogStart")] public float fogStart;
            [FieldOffset(88)][XdbName("FogEnd")] public float fogEnd;
            [FieldOffset(92)][XdbName("FogColor")] public int fogColor;
            [FieldOffset(96)][XdbName("FadeStart")] public float fadeStart;
            [FieldOffset(100)][XdbName("FadeEnd")] public float fadeEnd;
            [FieldOffset(104)][XdbName("DiffuseColor")] public int diffuseColor;
            [FieldOffset(108)][XdbName("ContourColor")] public int contourColor;
            [FieldOffset(112)][XdbName("AmbientFactor")] public float ambientFactor;
            [FieldOffset(116)][XdbName("AmbientColor")] public int ambientColor;
        }
    }
}
