// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum AlignY
{
    ALIGNY_DEFAULT = 0,
    ALIGNY_TOP = 1,
    ALIGNY_MIDDLE = 2,
    ALIGNY_BOTTOM = 3,
}
