// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum ExtendedType
{
    INTERACTION_NONE = 0,
    INTERACTION_BINDING_STONE = 1,
    INTERACTION_HERALD = 2,
    INTERACTION_GUILD_AUCTIONER = 3,
}
