// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum PrecastType
{
    PRECAST_DEFAULT = 0,
    PRECAST_ACTIONBARSTART = 1,
    PRECAST_LAUNCH = 2,
    PRECAST_NONE = 3,
}
