// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum ChargenEffectRunType
{
    CHARGEN_EFFECT_RUN_TYPE_KEY = 0,
    CHARGEN_EFFECT_RUN_TYPE_LOOP = 1,
}
