// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum DescriptionFormula
{
    WeaponScaler = 0,
    WeaponScalerMin = 1,
    WeaponScalerMax = 2,
    WeaponScalerSpeed = 3,
    WeaponScalerSpeedMin = 4,
    WeaponScalerSpeedMax = 5,
    RangedWeaponScaler = 6,
    RangedWeaponScalerMin = 7,
    RangedWeaponScalerMax = 8,
    RangedWeaponScalerSpeed = 9,
    RangedWeaponScalerSpeedMin = 10,
    RangedWeaponScalerSpeedMax = 11,
    MagicScaler = 12,
    MagicScalerWithoutRunes = 13,
    MagicBSVScaler = 14,
    MagicBSVScalerWithoutRunes = 15,
    PowBlank = 16,
    Shield = 17,
    PowSta = 18,
    DruidPet = 19,
    SummandInnateStatBaseBSV = 20,
    FairyHeal = 21,
    LevelScaler = 22,
    ManaLevelScaler = 23,
    DressSlotScaler = 24,
    DressSlotIndex = 25,
    FormulaUndefined = 26,
    FormulaSeconds = 27,
    FormulaPercent = 28,
    FormulaPercentAbsMinus1 = 29,
    FormulaPercent1MinusAbs = 30,
    LevelWeaponSpeed = 31,
    WeaponSpeed = 32,
    RangedWeaponSpeed = 33,
    FormulaBonusPool = 34,
    PetMelee = 35,
    PetMeleeMin = 36,
    PetMeleeMax = 37,
    RemortSpell = 38,
    RemortSpellWithoutRunes = 39,
    RemortSpellDamage = 40,
    RatingFiveStars = 41,
    AmmoDouble = 42,
    AmmoInc = 43,
    AmmoPowSpell = 44,
    AmmoPowSpellWithoutRunes = 45,
    AmmoPowMelee = 46,
    PlainText = 47,
    HealScaler = 48,
    HealScalerWithoutRunes = 49,
    HealBSVScaler = 50,
    HealBSVScalerWithoutRunes = 51,
}
