// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum EItemPriority
{
    DEFAULT = 0,
    RITUAL = 1,
    GUILD = 2,
    CUSTOM = 3,
    OVERLAP = 4,
    PREVIEW = 5,
    PREVIEW_RESERVE_0 = 6,
    PREVIEW_RESERVE_1 = 7,
    PREVIEW_RESERVE_2 = 8,
    PREVIEW_RESERVE_3 = 9,
    PREVIEW_RESERVE_4 = 10,
    PREVIEW_RESERVE_5 = 11,
    HIDE_ALL = 12,
}
