// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum FxLocators
{
    Global = 0,
    Head = 1,
    Chest = 2,
    Slot_Hand_L = 3,
    Slot_Hand_R = 4,
    Slot_Shoulder_L = 5,
    Slot_Shoulder_R = 6,
    Slot_FX = 7,
    Slot_TopFX = 8,
    Slot_Mouth = 9,
    Slot_Global = 10,
    Slot_Head = 11,
    Slot_BodyFX = 12,
    Wand_Slot_FX = 13,
    UsedObject_Slot_FX = 14,
    Slot_Glove_L = 15,
    Slot_Glove_R = 16,
    Slot_Locket = 17,
    Slot_Belt = 18,
    FROM_LOCATOR_NAME = 19,
}
