// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum InnateStats
{
    Plain = 0,
    Rage = 1,
    Finisher = 2,
    Lethality = 3,
    Vitality = 4,
    Endurance = 5,
    Lifesteal = 6,
    Will = 7,
    CritChance = 8,
}
