// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum MobDensity
{
    None = 0,
    Low = 1,
    Medium = 2,
    High = 3,
}
