// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum ModelMorphControl
{
    Height = 0,
    Head = 1,
    NeckThickness = 2,
    NeckLength = 3,
    Shoulders = 4,
    Torso = 5,
    Breast = 6,
    Waist = 7,
    Basin = 8,
    Hands = 9,
    Forearms = 10,
    Palm = 11,
    Hips = 12,
    Shins = 13,
    Feet = 14,
}
