// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum ToggleTarget
{
    All = 0,
    ShipConstructionProgress = 1,
    ShipRepairProgress = 2,
}
