// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V7_0_00_76.Enums;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public enum VesselSlot
{
    InvalidSlot = 0,
    ShipNose = 1,
    ShipBoard = 2,
    ShipTower = 3,
    ShipSternEngine = 4,
    ShipBase = 5,
    CannonLoophole = 6,
    RaygunLoophole = 7,
    SailsDeck = 8,
    Shield = 9,
    DamageAreaReactor = 10,
    DamageAreaEngine = 11,
    DamageAreaRudder = 12,
    DamageAreaScaner = 13,
    DamageAreaVisor = 14,
    DamageAreaAstralTrap = 15,
    DamageAreaNavigator = 16,
    CannonUp = 17,
    CannonDown = 18,
    CannonForward = 19,
    CannonForward01 = 20,
    CannonForward02 = 21,
    CannonLeftUp01 = 22,
    CannonLeftUp02 = 23,
    CannonLeftUp03 = 24,
    CannonLeftUp04 = 25,
    CannonLeftUp05 = 26,
    CannonRightUp01 = 27,
    CannonRightUp02 = 28,
    CannonRightUp03 = 29,
    CannonRightUp04 = 30,
    CannonRightUp05 = 31,
    CannonLeftDown01 = 32,
    CannonLeftDown02 = 33,
    CannonLeftDown03 = 34,
    CannonLeftDown04 = 35,
    CannonLeftDown05 = 36,
    CannonRightDown01 = 37,
    CannonRightDown02 = 38,
    CannonRightDown03 = 39,
    CannonRightDown04 = 40,
    CannonRightDown05 = 41,
}
