// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(108)]
[XdbName("gameMechanics.constructor.basicInterfaces.Action")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Action
{
    [FieldOffset(28)] public ContextActionInfo contextActionInfo;
    [FieldOffset(76)] public ResourcePointer[] groups;
    [FieldOffset(92)] public ResourcePointer[] interruptsActionGroups;

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ContextActionInfo
    {
        [FieldOffset(4)] public TextFileRef contextDescription;
        [FieldOffset(20)] public ResourcePointer contextImage;
        [FieldOffset(28)] public TextFileRef contextName;
        [FieldOffset(44)] public int priority;
    }
}
