// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(68)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AliasVisObjectTemplate
{
    [FieldOffset(24)][XdbName("Description")] public TextFileRef description;
    [FieldOffset(44)] public ResourcePointer resource;
    [FieldOffset(52)][EnumRef(typeof(Enums.AliasSearchPlace))] public int[] searchPlaces;
}

