// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(124)]
[XdbName("gameMechanics.constructor.schemes.item.AlternativeCurrency")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AlternativeCurrency
{
    [FieldOffset(24)] public ResourcePointer category;
    [FieldOffset(32)] public DescVar[] descVars;
    [FieldOffset(48)] public TextFileRef description;
    [FieldOffset(64)] public ResourcePointer image;
    [FieldOffset(72)] public ResourcePointer limitCurrency;
    [FieldOffset(80)] public int maxValue;
    [FieldOffset(84)] public TextFileRef name;
    //TODO: ENUM
    [FieldOffset(100)] public int storage;
    [FieldOffset(104)] public string sysName;
    //TODO: ENUM
    [FieldOffset(116)] public int visualizeMode;
    [FieldOffset(120)] public bool hideMaxValue;
    [FieldOffset(121)] public bool isClientReplicated;
    [FieldOffset(122)] public bool isCoupon;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DescVar
    {
        [FieldOffset(4)] public string name;
        [FieldOffset(16)] public NullablePointer scaler;
        [FieldOffset(20)] public TextFileRef text;
        [FieldOffset(36)] public float value;
    }
}
