// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(204)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AnimationProperties
{
    [FieldOffset(24)] public string headBoneName;
    [FieldOffset(36)] public float headTurnTime;
    //TODO: ENUM
    [FieldOffset(40)] public int kind;
    [FieldOffset(44)] public float legAlignTime;
    [FieldOffset(48)] public float legRunTurnTime;
    [FieldOffset(52)] public float maxHeadAngle;
    [FieldOffset(56)] public float run;
    [FieldOffset(60)] public SpecialShuffleParams specialShuffleParams;
    [FieldOffset(72)] public string spineBoneName;
    [FieldOffset(84)] public float swimHeight;
    [FieldOffset(88)] public TargetTrackingParams targetTrackingParams;
    [FieldOffset(180)] public float turnSpeedModifier;
    [FieldOffset(184)] public float walk;
    [FieldOffset(188)] public float walkBackwards;
    [FieldOffset(192)] public float walkForward;
    [FieldOffset(196)] public bool canWalkBackwards;
    [FieldOffset(197)] public bool finishMoveAnimation;
    [FieldOffset(198)] public bool forceMoveDisableUsed;
    [FieldOffset(199)] public bool groundNormalByBoundingBox;
    [FieldOffset(200)] public bool moveAnimationsNoScale;
    [FieldOffset(201)] public bool useWalkForward;

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SpecialShuffleParams
    {
        [FieldOffset(4)] public float minChangeRotationAngle;
        [FieldOffset(8)] public float minChangeVelocityAngle;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TargetTrackingParams
    {
        //TODO: ENUM
        [FieldOffset(4)] public int[] addedToUseAnimations;
        //TODO: ENUM
        [FieldOffset(20)] public int horizontalRotate;
        [FieldOffset(24)] public float maxHeadAngleToDown;
        [FieldOffset(28)] public float maxHeadAngleToSide;
        [FieldOffset(32)] public float maxHeadAngleToUp;
        [FieldOffset(36)] public string targetBoneName;
        [FieldOffset(48)] public float trackingTimeOut;
        [FieldOffset(52)] public Sound3D turnSound;
        //TODO: ENUM
        [FieldOffset(80)] public int verticalRotate;
        [FieldOffset(84)] public bool ingnoreRotateToTarget;
        [FieldOffset(85)] public bool noRotateBody;
        [FieldOffset(86)] public bool use;
        [FieldOffset(87)] public bool useInEveryAnimation;
        [FieldOffset(88)] public bool useOnlyAddedAnimations;
    }
}
