// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(68)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AnimationFromParentComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public AnimationsReplacement[] animationsReplacements;
    [FieldOffset(52)] public ResourcePointer controller;
    //TODO: ENUM
    [FieldOffset(60)] public int ifAnimationNotExistsRun;
    [FieldOffset(64)] public bool skipBlendOptimization;
    [FieldOffset(65)] public bool synchronizeAnimationPosition;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AnimationsReplacement
    {
        //TODO: ENUM
        [FieldOffset(4)] public int[] forAnimations;
        //TODO: ENUM
        [FieldOffset(20)] public int play;
    }
}
