// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(80)]
[XdbName("gameMechanics.world.bigAstral.AstralSectorResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public class AstralSectorResource
{
    [FieldOffset(76)] public bool allowChoiceLoot;
    [FieldOffset(40)] public TextFileRef description;
    [FieldOffset(24)] public DescVar[] descVars;
    [FieldOffset(77)] public bool isInstanced;
    [FieldOffset(56)] public int maxServerProgress;
    [FieldOffset(60)] public TextFileRef name;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DescVar
    {
        [FieldOffset(4)] public string name;
        [FieldOffset(16)] public NullablePointer scaler;
        [FieldOffset(20)] public TextFileRef text;
        [FieldOffset(36)] public float value;
    }
}
