// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[XdbName("gameMechanics.constructor.schemes.item.Bag")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Bag
{
    [FieldOffset(24)] public int baseSize;
    [FieldOffset(28)] public ResourcePointer shape;
}
