// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(36)]
[XdbName("gameMechanics.world.stronghold.Beast")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Beast
{
    [FieldOffset(24)] public ResourcePointer mob;
    [FieldOffset(32)][EnumRef(typeof(Enums.BeastType))] public int type;
}
