// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(72)]
[XdbName("itemService.basicElements.ChangeFactionRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ChangeFactionRoot
{
    [FieldOffset(24)] public PridenFactionChoice[] pridenFactionChoices;
    [FieldOffset(40)] public ResourcePointer spellDonateToEmpire;
    [FieldOffset(48)] public ResourcePointer spellDonateToLeague;
    [FieldOffset(56)] public ResourcePointer spellPridenToEmpire;
    [FieldOffset(64)] public ResourcePointer spellPridenToLeague;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PridenFactionChoice
    {
        [FieldOffset(4)] public ResourcePointer faction;
        [FieldOffset(12)][EnumRef(typeof(Enums.PridenFactionChoice))] public int[] values;
    }
}
