// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(124)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ChannelingComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public ResourcePointer channelingFx;
    [FieldOffset(44)] public StartPoint endPoint;
    [FieldOffset(80)] public float fxLength;
    [FieldOffset(84)] public StartPoint startPoint;
    [FieldOffset(120)] public bool scaleTextureU;
    [FieldOffset(121)] public bool scaleTextureV;

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class StartPoint
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.FxLocators))] public int locator;
        [FieldOffset(8)] public string locatorName;
        [FieldOffset(20)][EnumRef(typeof(Enums.ETroopMember))] public int member;
        [FieldOffset(24)] public Vector3 shift;
    }
}

