// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(60)]
[XdbName("gameMechanics.world.avatar.form.CharacterForm")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterForm
{
    [FieldOffset(24)][XdbName("Name")] public TextFileRef name;
    [FieldOffset(40)] public ResourcePointer image;
    [FieldOffset(48)] public string sysName;
}