// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(116)]
[XdbName("gameMechanics.world.avatar.CharacterRaceClass")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterRaceClass
{
    [FieldOffset(24)] public ResourcePointer characterClass;
    [FieldOffset(32)] public ResourcePointer characterRace;
    [FieldOffset(40)] public TextFileRef description;
    [FieldOffset(56)] public TextFileRef greatName;
    [FieldOffset(72)] public TextFileRef name;
    [FieldOffset(88)] public SpecialItemClasse[] specialItemClasses;
    [FieldOffset(104)] public string sysName;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SpecialItemClasse
    {
        [FieldOffset(4)] public ResourcePointer itemClass;
        [FieldOffset(12)] public int level;
    }
}
