// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(96)]
[XdbName("gameMechanics.world.avatar.CharacterRace")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterRace
{
    [FieldOffset(24)] public int changeRaceMinLevel;
    [FieldOffset(28)] public ResourcePointer[] changeRaceUnlocks;
    [FieldOffset(44)] public float corpulence;
    [FieldOffset(48)] public TextFileRef name;
    [FieldOffset(64)] public RaceSexDesc[] raceSexDescs;
    [FieldOffset(80)] public string sysName;
    [FieldOffset(92)] public bool allowToCreateFirstling;
    [FieldOffset(93)] public bool allowToCreateResetRemort;
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RaceSexDesc
    {
        [FieldOffset(4)] public TextFileRef name;
        //TODO: ENUM
        [FieldOffset(20)] public int sex;
    }
}