// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(136)]
[XdbName("gameMechanics.world.avatar.CharacterClass")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterClass
{
    [FieldOffset(24)][XdbName("Name")] public TextFileRef name;
    [FieldOffset(40)] public ResourcePointer[] characterForms;
    [FieldOffset(56)] public string className;
    [FieldOffset(68)] public float hitDice;
    [FieldOffset(72)] public ItemClasse[] itemClasses;
    [FieldOffset(88)] public float manaDice;
    //TODO: ENUM
    [FieldOffset(92)] public int manaType;
    [FieldOffset(96)] public ResourcePointer[] sharedAbilities;
    [FieldOffset(112)] public ResourcePointer[] sharedSpells;
    [FieldOffset(128)] public ResourcePointer talentsTable;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ItemClasse
    {
        [FieldOffset(4)] public ResourcePointer itemClass;
        [FieldOffset(12)] public int minLevel;
    }
}
