// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(56)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterSoundVariation
{
    [FieldOffset(24)] public AliasSound[] aliasSounds;
    [FieldOffset(40)] public AnimationSound[] animationSounds;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AliasSound
    {
        [FieldOffset(4)] public ResourcePointer alias;
        [FieldOffset(12)] public Sound3D sound;
    }

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AnimationSound
    {
        //TODO: ENUM
        [FieldOffset(4)] public int animation;
        [FieldOffset(8)] public Sound3D sound;
        [FieldOffset(36)] public bool noRepeatSoundOnAnimationLoop;
        [FieldOffset(37)] public bool replaceOriginalSound;
    }
}
