// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(56)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterAnimationsGroup
{
    //TODO: ENUM
    [FieldOffset(24)] public int[] allCharacterAnimations;
    [FieldOffset(40)] public CharacterAnimation[] characterAnimations;
    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CharacterAnimation
    {
        //TODO: ENUM
        [FieldOffset(4)] public int[] animations;
        [FieldOffset(20)] public ResourcePointer character;
    }
}