// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(68)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ClientContextActions
{
    [FieldOffset(24)] public ResourcePointer defaultExploit;
    [FieldOffset(32)] public ResourcePointer defaultMobVisualExploit;
    [FieldOffset(40)] public NamedAction[] namedActions;
    [FieldOffset(56)] public ResourcePointer questOperatorAction;
    [FieldOffset(64)] public float range;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class NamedAction
    {
        [FieldOffset(4)] public ResourcePointer action;
        [FieldOffset(12)] public string sysActionName;
    }
}
