// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(80)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ClientPetInfo
{
    //TODO: ENUM
    [FieldOffset(24)] public int blinkAnim;
    //TODO: ENUM
    [FieldOffset(28)] public int danceAnim;
    //TODO: ENUM
    [FieldOffset(32)] public int[] idleAnim;
    //TODO: ENUM
    [FieldOffset(48)] public int runAnim;
    [FieldOffset(52)] public ResourcePointer teleportFx;
    [FieldOffset(60)] public float teleportFxScale;
    [FieldOffset(64)] public float teleportFxShift;
    [FieldOffset(68)] public ResourcePointer visObj;
    //TODO: ENUM
    [FieldOffset(76)] public int walkAnim;
}
