// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(64)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Collision
{
    [FieldOffset(24)] public AABB aabb;
    [FieldOffset(48)] public ResourcePointer collisionMesh;
    //TODO: ENUM
    [FieldOffset(56)] public int volume;
    [FieldOffset(60)] public bool hasVisualCollision;
}