// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[XdbName("itemService.rules.components.contest.ContestRewardsWithPlaces")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ContestRewardsWithPlaces
{
    [FieldOffset(24)] public Entrie[] entries;

    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Entrie
    {
        [FieldOffset(4)] public Item[] items;
        [FieldOffset(20)] public NullablePointer[] places;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Item
        {
            [FieldOffset(4)] public ResourcePointer item;
            [FieldOffset(12)] public int stackCount;
            [FieldOffset(16)] public bool bound;
        }
    }
}
