// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(56)]
[XdbName("itemService.contestBox.ContestBoxResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ContestBoxResource
{
    [FieldOffset(24)] public ResourcePointer contestResource;
    [FieldOffset(32)] public ResourcePointer image;
    [FieldOffset(40)] public PrizeBanner[] prizeBanners;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PrizeBanner
    {
        [FieldOffset(4)] public ResourcePointer image;
        [FieldOffset(12)] public ResourcePointer item;
        [FieldOffset(20)][EnumRef(typeof(Enums.QualityEnum))] public int quality;
        [FieldOffset(24)] public bool isImportant;
    }
}

