// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(80)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureColorAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)][EnumRef(typeof(Enums.BlendMode))] public int blendMode;
    [FieldOffset(40)] public Quaternion colorFactor;
    [FieldOffset(56)] public int colorValue;
    [FieldOffset(60)] public int priority;
    [FieldOffset(64)] public float timeOff;
    [FieldOffset(68)] public float timeOn;
    [FieldOffset(72)][EnumRef(typeof(Enums.ERiderMember))] public int useOn;
    [FieldOffset(76)] public bool ignoreDisable;
}

