// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(52)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureVisState
{
    [FieldOffset(24)][EnumRef(typeof(Enums.Animations))] public int fixedIdleAnimation;
    [FieldOffset(28)] public float scale;
    [FieldOffset(32)] public int stateID;
    [FieldOffset(36)] public TransferScript[] transferScripts;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TransferScript
    {
        [FieldOffset(4)] public NullablePointer script;
        [FieldOffset(8)] public int toState;
    }
}
