// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(60)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureIntervalVisScripts
{
    [FieldOffset(24)][XdbName("Description")] public TextFileRef description;
    [FieldOffset(40)] public NullablePointer parameter;
    [FieldOffset(44)] public State[] states;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class State
    {
        [FieldOffset(4)] public NullablePointer allTimeScript;
        [FieldOffset(8)] public NullablePointer enterFromBiggerScript;
        [FieldOffset(12)] public NullablePointer enterFromLowerScript;
        [FieldOffset(16)] public float maxValue;
        [FieldOffset(20)] public bool playIfStateSkipedFromBigger;
        [FieldOffset(21)] public bool playIfStateSkipedFromLower;
    }
}
