// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CreatureOnCreationVisAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public NullablePointer visualScript;
    [FieldOffset(40)] public bool skipTransparencyFading;
}
