// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(52)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DayTimeComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public Interval[] intervals;
    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Interval
    {
        [FieldOffset(4)] public float endTime;
        [FieldOffset(8)] public float startTime;
    }
}