// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DeviceOfflineComponent
{
    [FieldOffset(24)] public NullablePointer malfunctionScript;
    [FieldOffset(28)] public NullablePointer offlineScript;
    [FieldOffset(32)] public NullablePointer onlineScript;
    [FieldOffset(36)] public NullablePointer overheatScript;
}
