// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(76)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DeviceAnimationAction
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(40)] public Advanced advanced;
    //TODO: ENUM
    [FieldOffset(52)] public int[] animations;
    [FieldOffset(68)] public int channelId;
    //TODO: ENUM
    [FieldOffset(72)] public int mode;

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Advanced
    {
        [FieldOffset(4)] public float speed;
        [FieldOffset(8)] public bool backgroundAfterFirstKey;
    }
}
