// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DeviceVisScripts
{
    [FieldOffset(24)] public NullablePointer defaultVisAction;
    [FieldOffset(28)] public State[] states;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class State
    {
        [FieldOffset(4)] public NullablePointer action;
        [FieldOffset(8)] public int prevState;
    }
}
