// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DiminishingRoot
{
    [FieldOffset(24)] public DiminishingGroup[] diminishingGroups;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DiminishingGroup
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.EControlType))] public int controlType;
        [FieldOffset(8)] public ResourcePointer[] levels;
    }
}

