// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(80)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DressSlotSettings
{
    [FieldOffset(24)] public AddedComponent[] addedComponents;
    [FieldOffset(40)] public ResourcePointer emptyVisItem;
    [FieldOffset(48)][EnumRef(typeof(Enums.DressSlot))] public int[] slotOrder;
    [FieldOffset(64)] public VisItemFallback[] visItemFallbacks;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AddedComponent
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.DressSlot))] public int dressSlot;
        [FieldOffset(8)] public NullablePointer[] dynamicComponents;
        [FieldOffset(24)] public NullablePointer[] staticComponents;
    }

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class VisItemFallback
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.DressSlot))] public int dressSlot;
        [FieldOffset(8)] public ResourcePointer visItem;
    }
}

