// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(124)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class EmitterVisObjComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public int delay;
    [FieldOffset(40)] public string locatorName;
    [FieldOffset(52)] public Vector3 maxAngles;
    [FieldOffset(64)] public float maxScale;
    [FieldOffset(68)] public Vector3 minAngles;
    [FieldOffset(80)] public float minScale;
    [FieldOffset(84)] public Vector3 offset;
    [FieldOffset(96)] public float radius;
    [FieldOffset(100)] public float rate;
    [FieldOffset(104)] public ResourcePointer[] visObjects;
    [FieldOffset(120)] public bool fixedPoint;
}
