// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(60)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class EntityVisActionIfVisObject
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(40)] public NullablePointer defaultVisAction;
    [FieldOffset(44)] public VisObjectMatche[] visObjectMatches;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class VisObjectMatche
    {
        [FieldOffset(4)] public NullablePointer visAction;
        [FieldOffset(8)] public ResourcePointer visObject;
    }
}
