// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(72)]
[XdbName("gameMechanics.constructor.schemes.fairy.FairyResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class FairyResource
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public ResourcePointer levelChangedScript;
    [FieldOffset(48)] public TextFileRef name;
    [FieldOffset(64)] public ResourcePointer zodiacSign;
}