// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class FoliageGeometry
{
    [FieldOffset(24)] public Quad[] quads;
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Quad
    {
        [FieldOffset(4)] public float u;
        [FieldOffset(8)] public float v;
        [FieldOffset(12)] public float x;
        [FieldOffset(16)] public float y;
        [FieldOffset(20)] public float z;
    }
}