// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(792)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GMUIHelper
{
    [FieldOffset(24)] public AbilitiesAliase[] abilitiesAliases;
    [FieldOffset(40)] public ResourcePointer aedRace;
    [FieldOffset(48)] public DeniedTag[] allowedTags;
    [FieldOffset(64)] public ResourcePointer antiFlood;
    [FieldOffset(72)] public ResourcePointer antiSpam;
    [FieldOffset(80)] public AuctionFilter auctionFilter;
    [FieldOffset(132)] public ResourcePointer buffGroupDiseases;
    [FieldOffset(140)] public ResourcePointer buffGroupMagics;
    [FieldOffset(148)] public ResourcePointer buffGroupPoisons;
    [FieldOffset(156)] public ResourcePointer castbarGroup;
    [FieldOffset(164)] public ResourcePointer checkRoomRoot;
    [FieldOffset(172)] public TextFileRef chestOpening;
    [FieldOffset(192)] public ClassSpecificData classSpecificData;
    [FieldOffset(212)] public TextFileRef completeQuestText;
    [FieldOffset(228)] public ResourcePointer conditionEvents;
    [FieldOffset(236)] public ResourcePointer contextActions;
    [FieldOffset(244)] public ResourcePointer[] currencies;
    [FieldOffset(260)] public DeniedTag[] deniedTags;
    [FieldOffset(276)] public ResourcePointer[] detectors;
    [FieldOffset(292)] public ResourcePointer elfRace;
    [FieldOffset(300)] public ResourcePointer empireFaction;
    [FieldOffset(308)] public ResourcePointer[] engineerAssistentSpells;
    [FieldOffset(324)] public EquipmentData equipmentData;
    [FieldOffset(348)] public ResourcePointer escapeDungeonSpell;
    [FieldOffset(356)] public ResourcePointer[] forgeGoldenSlots;
    [FieldOffset(372)] public ResourcePointer[] forgeResources;
    [FieldOffset(388)] public ResourcePointer freeKeysSpell;
    [FieldOffset(396)] public TextFileRef gameItemCompositNameSpace;
    [FieldOffset(412)] public ResourcePointer gameStateRoot;
    [FieldOffset(420)] public ResourcePointer gibberlingRace;
    [FieldOffset(428)] public ResourcePointer hadaganRace;
    [FieldOffset(436)] public ResourcePointer heroesArenaQuitSpell;
    [FieldOffset(444)] public ResourcePointer heroesArenaStarnStageSpell;
    [FieldOffset(452)] public ResourcePointer interfaceMaps;
    [FieldOffset(460)] public ResourcePointer itemMall;
    [FieldOffset(468)] public ResourcePointer kaniaRace;
    [FieldOffset(476)] public ResourcePointer leagueFaction;
    [FieldOffset(484)] public ResourcePointer notifications;
    [FieldOffset(492)] public ResourcePointer orcRace;
    [FieldOffset(500)] public ResourcePointer poweredLSWeaponsRoot;
    [FieldOffset(508)] public ResourcePointer[] pridenFactions;
    [FieldOffset(524)] public ResourcePointer pridenRace;
    [FieldOffset(532)] public ResourcePointer[] psionicAssistentSpells;
    [FieldOffset(548)] public ResourcePointer ratingArena3x3;
    [FieldOffset(556)] public ResourcePointer ratingArena6x6;
    [FieldOffset(564)] public ResourcePointer ratingHPI;
    [FieldOffset(572)] public ResourcePointer referralContentKey;
    [FieldOffset(580)] public ResourcePointer[] reforgeDefResources;
    [FieldOffset(596)] public ResourcePointer[] reforgeOffResources;
    [FieldOffset(612)] public ResourcePointer[] remindedTemporaryUnlocks;
    [FieldOffset(628)] public ResourcePointer[] riftMaps;
    [FieldOffset(644)] public ResourcePointer ruleNews;
    [FieldOffset(652)] public ResourcePointer runProceduralDungeonScenarioSpell;
    [FieldOffset(660)] public ResourcePointer slashCommands;
    [FieldOffset(668)] public ResourcePointer socialNetwork;
    [FieldOffset(676)] public ResourcePointer stopProceduralDungeonScenarioSpell;
    [FieldOffset(684)] public ResourcePointer tutorialRoot;
    [FieldOffset(692)] public ResourcePointer undeadRace;
    [FieldOffset(700)] public UnlocksSpecial unlocksSpecial;
    [FieldOffset(752)] public UnstuckSpell unstuckSpell;
    [FieldOffset(772)] public ResourcePointer variablesAliases;
    [FieldOffset(780)] public ResourcePointer veteranRewards;
    [FieldOffset(788)] public float warningLowStatPercent;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DeniedTag
    {
        [FieldOffset(4)] public ResourcePointer contentKey;
        [FieldOffset(12)] public string[] tags;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ClassSpecificData
    {
        [FieldOffset(0)] public Stalker stalker;

        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Stalker
        {
            [FieldOffset(4)] public Arrow[] arrows;

            [StructSize(32)]
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class Arrow
            {
                [FieldOffset(4)] public string alias;
                [FieldOffset(16)] public ResourcePointer enchatSpell;
                [FieldOffset(24)] public ResourcePointer shotSpell;
            }
        }
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AbilitiesAliase
    {
        [FieldOffset(4)] public ResourcePointer ability;
        [FieldOffset(12)] public string alias;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class UnlocksSpecial
    {
        [FieldOffset(4)] public ResourcePointer greatnessUnlock;
        [FieldOffset(12)] public TextFileRef metamorphNameMask;
        [FieldOffset(28)] public ResourcePointer metamorphUnlock;
        [FieldOffset(36)] public ResourcePointer[] promotionUnlocks;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class UnstuckSpell
    {
        [FieldOffset(4)] public ResourcePointer contentKey;
        [FieldOffset(12)] public ResourcePointer spell;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class EquipmentData
    {
        [FieldOffset(4)] public int presetsCount;
        [FieldOffset(8)][EnumRef(typeof(Enums.DressSlot))] public int[] slots;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AuctionFilter
    {
        [FieldOffset(4)] public ResourcePointer defaultItemClass;
        [FieldOffset(12)] public ResourcePointer defaultItemQuality;
        [FieldOffset(20)] public ItemQualitie[] itemClasses;
        [FieldOffset(36)] public ItemQualitie[] itemQualities;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class ItemQualitie
        {
            [FieldOffset(4)] public string alias;
            [FieldOffset(16)] public ResourcePointer item;
        }
    }
}
