// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(28)]
[XdbName("gameMechanics.world.social.guild.symbolics.GuildSymbolicsChanger")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GuildSymbolicsChanger
{
    [FieldOffset(24)] public bool ableToUpdate;
}