// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(76)]
[XdbName("gameMechanics.world.social.guild.base.GuildRankResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GuildRankResource
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public TextFileRef name;
    [FieldOffset(56)] public ResourcePointer rightsPreset;
    [FieldOffset(64)] public string sysName;
}