// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[XdbName("gameMechanics.world.social.guild.base.GuildProgressRewards")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GuildProgressRewards
{
    [FieldOffset(24)] public Entrie[] entries;
    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Entrie
    {
        [FieldOffset(4)] public int level;
        [FieldOffset(8)] public NullablePointer reward;
    }
}