// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class IfCreatureVisCharacter
{
    [FieldOffset(24)] public ResourcePointer[] visCharList;
    [FieldOffset(40)] public bool checkIsInTheList;
    [FieldOffset(41)] public bool checkOnStartOnly;
}
