// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class InterfaceMapObjects
{
    [FieldOffset(24)] public Marker[] markers;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Marker
    {
        [FieldOffset(4)] public ResourcePointer marker;
        [FieldOffset(12)] public Object[] objects;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Object
        {
            [FieldOffset(4)] public int x;
            [FieldOffset(8)] public int y;
            [FieldOffset(12)] public int z;
            [FieldOffset(16)] public ResourcePointer zone;
        }
    }
}
