// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(112)]
[XdbName("gameMechanics.interactions.common.Interactions")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Interactions
{
    [FieldOffset(20)][EnumRef(typeof(Enums.ItemSlotType))] public int[] accessorFor;
    [FieldOffset(36)] public ResourcePointer auction;
    [FieldOffset(44)] public ResourcePointer[] availableQuests;
    [FieldOffset(60)] public Cue[] cues;
    [FieldOffset(76)][EnumRef(typeof(Enums.ExtendedType))] public int[] extended;
    [FieldOffset(92)] public NullablePointer teleportMaster;
    [FieldOffset(96)] public NullablePointer trainer;
    [FieldOffset(100)] public ResourcePointer vendorTable;
    [FieldOffset(108)] public bool changeRoomMaster;
    [FieldOffset(109)] public bool isMailBox;
    [FieldOffset(110)] public bool isMetaItemUpgrader;
    [FieldOffset(111)] public bool remortMaster;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Cue
    {
        [FieldOffset(4)] public ResourcePointer cue;
    }
}

