// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(192)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class InterfaceMap
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public ResourcePointer finalQuest;
    [FieldOffset(48)] public ResourcePointer[] mapResources;
    [FieldOffset(64)] public ResourcePointer markerObjects;
    [FieldOffset(72)] public int maxComfortLevel;
    [FieldOffset(76)] public int minComfortLevel;
    [FieldOffset(80)] public TextFileRef name;
    [FieldOffset(96)] public ResourcePointer otherQuestsMap;
    [FieldOffset(104)] public NullablePointer[] presencePredicates;
    [FieldOffset(120)] public ResourcePointer quests;
    [FieldOffset(128)] public NullablePointer[] showPredicates;
    [FieldOffset(144)] public string sysName;
    [FieldOffset(156)] public ResourcePointer texture;
    [FieldOffset(164)] public int zoneCeil;
    [FieldOffset(168)] public int zoneFloor;
    [FieldOffset(172)] public ZoneInset[] zoneInsets;
    [FieldOffset(188)] public bool showInList;
    [FieldOffset(189)] public bool showPositions;
    [FieldOffset(190)] public bool showQuestProgress;

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ZoneInset
    {
        [FieldOffset(4)] public int height;
        [FieldOffset(8)] public ResourcePointer[] otherQuestZones;
        [FieldOffset(24)] public int width;
        [FieldOffset(28)] public int x;
        [FieldOffset(32)] public int y;
        [FieldOffset(36)] public ResourcePointer[] zones;
    }
}
