// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(92)]
[XdbName("itemService.loginEvent.LoginEventReward")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class LoginEventReward
{
    [FieldOffset(24)] public ResourcePointer[] bronze;
    [FieldOffset(40)] public int bronzeCount;
    [FieldOffset(44)] public int day;
    [FieldOffset(48)] public ResourcePointer[] gold;
    [FieldOffset(64)] public int goldCount;
    [FieldOffset(68)] public ResourcePointer[] silver;
    [FieldOffset(84)] public int silverCount;
    [FieldOffset(88)] public bool ignoreLevelCap;
}
