// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(56)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class LotteryBoxRoot
{
    [FieldOffset(24)] public BoxObject[] boxObjects;
    [FieldOffset(40)] public CommonObject[] commonObjects;

    [StructSize(60)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CommonObject
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.Animations))] public int idleAnimation;
        [FieldOffset(8)] public ResourcePointer item;
        [FieldOffset(16)][XdbName("object")] public ResourcePointer @object;
        [FieldOffset(24)] public Vector3 position;
        [FieldOffset(36)] public int rotate;
        [FieldOffset(40)] public float scale;
        [FieldOffset(44)][EnumRef(typeof(Enums.Animations))] public int[] winAnimations;
    }

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class BoxObject
    {
        [FieldOffset(4)] public ResourcePointer item;
        [FieldOffset(12)] public Object[] objects;

        [StructSize(60)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Object
        {
            [FieldOffset(4)][EnumRef(typeof(Enums.Animations))] public int idleAnimation;
            [FieldOffset(8)] public ResourcePointer item;
            [FieldOffset(16)][XdbName("object")] public ResourcePointer @object;
            [FieldOffset(24)] public Vector3 position;
            [FieldOffset(36)] public int rotate;
            [FieldOffset(40)] public float scale;
            [FieldOffset(44)][EnumRef(typeof(Enums.Animations))] public int[] winAnimations;
        }
    }
}

