// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(68)]
[XdbName("gameMechanics.map.variables.MapVariableResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class MapVariableResource
{
    [FieldOffset(24)] public NullablePointer maxValue;
    [FieldOffset(28)] public NullablePointer minValue;
    [FieldOffset(32)] public TextFileRef name;
    [FieldOffset(48)] public string sysName;
    [FieldOffset(60)] public bool resetOnStretch;
}
