// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(348)]
[XdbName("gameMechanics.constructor.schemes.mount.MountResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class MountResource
{
    [FieldOffset(28)] public ContextActionInfo contextActionInfo;
    [FieldOffset(76)] public ResourcePointer[] groups;
    [FieldOffset(92)] public ResourcePointer[] interruptsActionGroups;
    [FieldOffset(112)][XdbName("Name")] public TextFileRef name;
    [FieldOffset(128)] public ResourcePointer[] abilities;
    [FieldOffset(144)] public ResourcePointer alternativeSkins;
    [FieldOffset(152)] public ResourcePointer basicSkin;
    [FieldOffset(160)] public ResourcePointer[] contextActions;
    [FieldOffset(176)] public float corpulence;
    [FieldOffset(180)] public DescVar[] descVars;
    [FieldOffset(196)] public TextFileRef description;
    [FieldOffset(212)] public int grade;
    [FieldOffset(216)] public Mechanics mechanics;
    [FieldOffset(256)] public ResourcePointer[] overrideMounts;
    [FieldOffset(272)] public NullablePointer penaltyCalcer;
    [FieldOffset(276)] public ResourcePointer[] spells;
    [FieldOffset(292)] public string sysName;
    [FieldOffset(304)] public TalentSlot[] talentSlots;
    [FieldOffset(320)] public TimeLeft timeLeft;
    [FieldOffset(344)] public bool canBeMorphed;
    [FieldOffset(345)] public bool isExoMount;
    [FieldOffset(346)] public bool isProbe;

    [StructSize(56)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TalentSlot
    {
        [FieldOffset(4)] public ResourcePointer[] availableTalents;
        [FieldOffset(20)] public TextFileRef description;
        [FieldOffset(36)] public TextFileRef name;
        [FieldOffset(52)] public bool hasCustomRank;
    }

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DescVar
    {
        [FieldOffset(4)] public string name;
        [FieldOffset(16)] public NullablePointer scaler;
        [FieldOffset(20)] public TextFileRef text;
        [FieldOffset(36)] public float value;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TimeLeft
    {
        [FieldOffset(4)] public int day;
        [FieldOffset(8)] public int hour;
        [FieldOffset(12)] public int minute;
        [FieldOffset(16)] public int ms;
        [FieldOffset(20)] public int second;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Mechanics
    {
        [FieldOffset(4)] public float health;
        [FieldOffset(8)] public float healthDelta;
        [FieldOffset(12)] public int healthLevelDelta;
        [FieldOffset(16)] public int prepareDuration;
        [FieldOffset(20)] public int prepareDurationDelta;
        [FieldOffset(24)] public float regen;
        [FieldOffset(28)] public float speed;
        [FieldOffset(32)] public float speedDelta;
        [FieldOffset(36)] public bool ignoreWater;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ContextActionInfo
    {
        [FieldOffset(4)] public TextFileRef contextDescription;
        [FieldOffset(20)] public ResourcePointer contextImage;
        [FieldOffset(28)] public TextFileRef contextName;
        [FieldOffset(44)] public int priority;
    }
}
