// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(108)]
[XdbName("order.OrderResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class OrderResource
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public ResourcePointer enterOrderSpell;
    [FieldOffset(48)] public ResourcePointer image;
    [FieldOffset(56)] public TextFileRef name;
    [FieldOffset(72)] public ResourcePointer prestigeEvent;
    [FieldOffset(80)] public ResourcePointer[] ratingEvents;
    [FieldOffset(96)] public string sysName;
}