// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(96)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PlayerCameraSettings
{
    [FieldOffset(24)] public Autoreturn autoreturn;
    [FieldOffset(44)] public float fovStep;
    [FieldOffset(48)] public float maxTransparencyDistance;
    [FieldOffset(52)] public float maxZoomDistance;
    [FieldOffset(56)] public float maxZoomStep;
    [FieldOffset(60)] public float minTransparencyDistance;
    [FieldOffset(64)] public float minZoomDistance;
    [FieldOffset(68)] public float minZoomStep;
    [FieldOffset(72)] public float zoomStep;
    [FieldOffset(76)] public ZoomStep[] zoomSteps;
    [FieldOffset(92)] public bool headBob;
    [FieldOffset(93)] public bool smartAutoreturn;
    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ZoomStep
    {
        [FieldOffset(4)] public float minDistance;
        [FieldOffset(8)] public float step;
    }
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Autoreturn
    {
        [FieldOffset(4)] public float panSpeed;
        [FieldOffset(8)] public float tlitSpeed;
        //TODO: ENUM
        [FieldOffset(12)] public int type;
        [FieldOffset(16)] public float zoomSpeed;
    }
}