// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(96)]
[XdbName("avatarPopulation.service.post.PostType")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PostType
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public int lengthLimit;
    [FieldOffset(44)] public TextFileRef name;
    [FieldOffset(60)] public NullablePointer[] posterConditions;
    [FieldOffset(76)] public int postsLimit;
    [FieldOffset(80)] public string sysName;
    [FieldOffset(92)] public bool isPersistent;
}
