// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(136)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PostEffectParams
{
    [FieldOffset(24)] public BlurAddFactor blurAddFactor;
    [FieldOffset(60)] public float blurRadius;
    [FieldOffset(64)] public BlurAddFactor diffuseFactor;
    [FieldOffset(100)] public BlurAddFactor overlayFactor;
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class BlurAddFactor
    {
        [FieldOffset(4)] public Quaternion add;
        [FieldOffset(20)] public Quaternion mul;
    }
}