// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(52)]
[XdbName("gameMechanics.elements.predicates.PredicateNear")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PredicateNear
{
    [FieldOffset(24)] public bool hideText;
    [FieldOffset(32)] public NullablePointer[] predicates;
    [FieldOffset(48)] public float radius;
}