// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(56)]
[XdbName("gameMechanics.elements.predicates.PredicateHasItemsCount")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PredicateHasItemsCount
{
    [FieldOffset(24)] public bool hideText;
    [FieldOffset(32)] public ResourcePointer[] items;
    [FieldOffset(48)] public int totalCount;
    [FieldOffset(52)] public bool checkBag;
    [FieldOffset(53)] public bool checkDress;
}
