// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(80)]
[XdbName("gameMechanics.world.gameRoot.PremiumStageEntry")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class PremiumStageEntry
{
    [FieldOffset(24)] public ResourcePointer[] buffs;
    [FieldOffset(40)] public TextFileRef description;
    [FieldOffset(56)] public ResourcePointer[] items;
    [FieldOffset(72)] public int requiredDonate;
    [FieldOffset(76)] public int stageNumber;
}