// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(60)]
[XdbName("gameMechanics.constructor.schemes.quest.chain.QuestsChainResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class QuestsChainResource
{
    [FieldOffset(24)] public TextFileRef name;
    [FieldOffset(40)] public ResourcePointer[] nodes;
    [FieldOffset(56)] public NullablePointer reward;
}
