// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(168)]
[XdbName("gameMechanics.elements.quest.QuestCountQuest")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class QuestCountQuest
{
    [FieldOffset(20)] public ResourcePointer[] autoRelatedItems;
    [FieldOffset(36)] public TextFileRef customName;
    [FieldOffset(52)] public TextFileRef description;
    [FieldOffset(68)][EnumRef(typeof(Enums.DressSlot))] public int[] dressSlots;
    [FieldOffset(84)] public int limit;
    [FieldOffset(88)] public Location[] locations;
    [FieldOffset(104)] public LootTable[] lootTables;
    [FieldOffset(120)] public ResourcePointer[] relatedItems;
    [FieldOffset(136)] public ResourcePointer[] relatedMobsAndDevices;
    [FieldOffset(152)] public bool alwaysShowMarker;
    [FieldOffset(153)] public bool alwaysShowRelatedMobsAndDevices;
    [FieldOffset(154)] public bool isInternal;
    [FieldOffset(155)] public bool showCounterValue;
    [FieldOffset(160)] public ResourcePointer quest;

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class LootTable
    {
        [FieldOffset(4)] public ResourcePointer item;
        [FieldOffset(12)] public ResourcePointer lootable;
    }

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Location
    {
        [FieldOffset(4)] public BigVector3 position;
        [FieldOffset(28)] public float radius;
        [FieldOffset(32)] public ResourcePointer zone;
        [FieldOffset(40)] public bool isIndoor;
    }
}

