// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(120)]
[XdbName("gameMechanics.constructor.schemes.skill.Recipe")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Recipe
{
    [FieldOffset(24)] public ResourcePointer afflatusItem;
    [FieldOffset(32)] public TextFileRef description;
    [FieldOffset(48)] public ResourcePointer image;
    [FieldOffset(56)] public TextFileRef name;
    [FieldOffset(72)] public ResourcePointer nextRecipe;
    [FieldOffset(80)] public int nextRecipePoints;
    [FieldOffset(84)] public ResourcePointer nextRecipeResource;
    [FieldOffset(92)] public ResourcePointer qualificationPoints;
    [FieldOffset(100)] public NullablePointer recipeInfo;
    [FieldOffset(104)] public NullablePointer result;
    [FieldOffset(108)] public int resultQuantity;
    [FieldOffset(112)] public int skillScore;
    [FieldOffset(116)] public bool bindResult;
}
