// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(60)]
[XdbName("gameMechanics.elements.resources.ResourceIncVariable")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ResourceIncVariable
{
    [FieldOffset(24)] public bool hideText;
    [FieldOffset(36)] public ResourcePointer ability;
    [FieldOffset(44)] public ResourcePointer variable;
    [FieldOffset(56)] public float inc;
}
