// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(52)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class RotateJointComponent
{
    [FieldOffset(20)][XdbName("VisualObjectComponentID")] public string visualObjectComponentID;
    [FieldOffset(36)] public Joint[] joints;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Joint
    {
        [FieldOffset(4)] public string jointName;
        [FieldOffset(16)][EnumRef(typeof(Enums.Axis))] public int rotationAxis;
        [FieldOffset(20)] public float rotationSpeed;
        [FieldOffset(24)] public float scale;
    }
}

