// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[XdbName("gameMechanics.map.tour.Route")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Route
{
    [FieldOffset(24)] public Point[] points;
    [FieldOffset(40)] public bool dropAtEnd;
    [FieldOffset(41)] public bool isClosed;
    [FieldOffset(42)] public bool showEndFog;
    [FieldOffset(43)] public bool showStartFog;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Point
    {
        [FieldOffset(4)] public Vector3 coord;
        [FieldOffset(16)] public int latency;
        [FieldOffset(20)] public float length;
        [FieldOffset(24)] public float speed;
        [FieldOffset(28)] public Vector3 tangent;
    }
}
