// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(76)]
[XdbName("gameMechanics.world.bigAstral.ScanerPOI")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ScanerPOI
{
    [FieldOffset(28)] public ResourcePointer collision;
    [FieldOffset(36)] public TextFileRef description;
    [FieldOffset(52)] public TextFileRef name;
    [FieldOffset(68)] public ResourcePointer obj;
}