// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SFXMaterialPairTable
{
    [FieldOffset(24)] public PairSound[] pairSounds;
    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PairSound
    {
        //TODO: ENUM
        [FieldOffset(4)] public int materialFirst;
        //TODO: ENUM
        [FieldOffset(8)] public int materialSecond;
        [FieldOffset(12)] public Sound3D sound;
    }
}