// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ShipNameGeneratingInfo
{
    [FieldOffset(24)] public FactionName[] factionNames;
    [FieldOffset(40)] public int maxNumber;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class FactionName
    {
        [FieldOffset(4)] public ResourcePointer faction;
        [FieldOffset(12)] public TextFileRef names;
    }
}
