// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(48)]
[XdbName("gameMechanics.map.zone.ShipBattleground")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ShipBattleground
{
    [FieldOffset(24)] public bool isInvitesAllowed;
    [FieldOffset(32)] public ResourcePointer[] neutralFactions;
}
