// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(108)]
[XdbName("gameMechanics.world.ship.ShipResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ShipResource
{
    [FieldOffset(24)] public NullablePointer[] parts;
    [FieldOffset(44)] public float corpulence;
    [FieldOffset(48)] public TextFileRef name;
    [FieldOffset(64)] public NullablePointer spawnLocation;
    [FieldOffset(68)] public bool manualCorpulence;
    [FieldOffset(76)] public int health;
    [FieldOffset(80)] public ResourcePointer image;
    [FieldOffset(88)] public VisualShip[] visualShips;
    [FieldOffset(104)] public bool drawInterface;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class VisualShip
    {
        [FieldOffset(4)] public ResourcePointer visualShip;
    }
}
