// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(296)]
[XdbName("socialNetworks.SocialNetworkDescription")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SocialNetworkDescription
{
    [FieldOffset(24)] public Abilities abilities;
    [FieldOffset(48)] public TextFileRef displayName;
    [FieldOffset(64)] public ResourcePointer image;
    [FieldOffset(72)] public ResourcePointer imageSmall;
    [FieldOffset(80)] public PostStyle[] postStyles;
    [FieldOffset(96)] public ScriptLocalizationTest script;
    [FieldOffset(136)] public ScriptLocalizationTest scriptLocalization;
    [FieldOffset(176)] public ScriptLocalizationTest scriptLocalizationTest;
    [FieldOffset(216)] public string shortName;
    [FieldOffset(236)] public Style style;
    [FieldOffset(292)] public bool excluded;
    [StructSize(48)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class PostStyle
    {
        [FieldOffset(4)] public ResourcePointer content;
        [FieldOffset(12)] public TextFileRef customLink;
        [FieldOffset(28)] public TextFileRef icon;
        [FieldOffset(44)] public bool addLink;
    }
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ScriptLocalizationTest
    {
        [FieldOffset(4)] public string[] dependencies;
        [FieldOffset(20)] public string main;
    }
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Style
    {
        [FieldOffset(0)] public LoginPage loginPage;
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class LoginPage
        {
            [FieldOffset(0)] public ModificationScript modificationScript;
            [FieldOffset(40)] public Vector2 size;
            [FieldOffset(48)] public int zoom;
            [FieldOffset(52)] public bool allowTransparentBackground;
            [FieldOffset(53)] public bool noRefreshOnLoading;
            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class ModificationScript
            {
                [FieldOffset(4)] public string[] dependencies;
                [FieldOffset(20)] public string main;
            }
        }
    }
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Abilities
    {
        [FieldOffset(4)] public int pictureCommentMaxLength;
        [FieldOffset(8)] public ResourcePointer textMessageLimit;
        [FieldOffset(16)] public int textMessageMaxLength;
        [FieldOffset(20)] public bool postPicture;
        [FieldOffset(21)] public bool postText;
    }
}