// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(200)]
[XdbName("gameMechanics.world.gameRoot.SpellRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SpellRoot
{
    [FieldOffset(24)] public ResourcePointer dispelBuffs;
    [FieldOffset(32)] public int globalCooldown;
    [FieldOffset(36)] public GoldenSlotsRoot goldenSlotsRoot;
    [FieldOffset(96)] public ResourcePointer groupEnchantedArrow;
    [FieldOffset(104)] public ResourcePointer groupFairySpells;
    [FieldOffset(112)] public ResourcePointer groupTwoEnchantedArrows;
    [FieldOffset(120)] public ResourcePointer hearthstoneSpell;
    [FieldOffset(128)] public ResourcePointer hearthstoneSpellImpl;
    [FieldOffset(136)] public ResourcePointer meleeSpell;
    [FieldOffset(144)] public int minTalentSelectLevel;
    [FieldOffset(148)] public ResourcePointer noSpell;
    [FieldOffset(156)] public ResourcePointer rangeSpell;
    [FieldOffset(164)] public ResourcePointer switchTalentBuild;
    [FieldOffset(172)] public WillImmunityBuffDuration willImmunityBuffDuration;
    [FieldOffset(196)] public bool noNeedInFront;

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class GoldenSlotsRoot
    {
        [FieldOffset(4)] public NullablePointer[] canPutOnPredicates;
        [FieldOffset(20)] public ResourcePointer[] destroyableItemClasses;
        [FieldOffset(36)] public ResourcePointer[] goldenSlotPacks;
        [FieldOffset(52)] public ResourcePointer spellPointsCurrency;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class WillImmunityBuffDuration
    {
        [FieldOffset(4)] public int day;
        [FieldOffset(8)] public int hour;
        [FieldOffset(12)] public int minute;
        [FieldOffset(16)] public int ms;
        [FieldOffset(20)] public int second;
    }
}
