// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(48)]
[XdbName("gameMechanics.constructor.schemes.item.SuffixItemProvider")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SuffixItemProvider
{
    [FieldOffset(24)] public ResourcePointer namer;
    [FieldOffset(32)] public ResourcePointer resource;
    [FieldOffset(40)] public ResourcePointer suffix;
}
