// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(64)]
[XdbName("gameMechanics.elements.scenarios.eventGoals.SurviveEventGoal")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SurviveEventGoal
{
    [FieldOffset(24)] public TextFileRef description;
    [FieldOffset(40)] public TextFileRef objective;
}
