// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[XdbName("itemService.elements.targetSales.TargetSaleResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TargetSaleResource
{
    [FieldOffset(24)] public Entrie[] entries;

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Entrie
    {
        [FieldOffset(4)] public NullablePointer amount;
        [FieldOffset(8)] public ResourcePointer baseItem;
        [FieldOffset(16)] public ResourcePointer itemMallItem;
        //TODO: ENUM
        [FieldOffset(24)] public int tag;
        [FieldOffset(28)] public TextFileRef text;
    }
}
