// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[XdbName("gameMechanics.elements.scalers.TargetBuffStackCountScaler")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TargetBuffStackCountScaler
{
    [FieldOffset(24)] public ResourcePointer buff;
    [FieldOffset(32)] public float mul;
    [FieldOffset(36)] public float sum;
    [FieldOffset(40)] public bool anyRank;
    [FieldOffset(41)] public bool onlyFromMaster;
}