// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[XdbName("timeinterval.TimeIntervalTable")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TimeIntervalTable
{
    [FieldOffset(24)] public Interval[] intervals;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Interval
    {
        [FieldOffset(4)] public NullablePointer finish;
        [FieldOffset(8)] public NullablePointer start;
    }
}
