// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UIRelatedSounds
{
    [FieldOffset(24)][XdbName("Items")] public Item[] items;

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Item
    {
        [FieldOffset(4)] public string name;
        [FieldOffset(16)] public Sound2D resource;
    }
}
