// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(68)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UITextFilter
{
    [FieldOffset(24)] public WString additionalChars;
    [FieldOffset(36)] public WString firstChars;
    [FieldOffset(48)] public Range[] ranges;
    [FieldOffset(64)] public bool isAllowObject;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Range
    {
        [FieldOffset(4)] public WString maxChar;
        [FieldOffset(16)] public WString minChar;
    }
}
