// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[XdbName("gameMechanics.constructor.schemes.item.meta.UniversalMetaUpgrader")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UniversalMetaUpgrader
{
    [FieldOffset(28)] public ResourcePointer[] upgrades;
}