// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(88)]
[XdbName("itemService.avatar.itemBag.UseOnMountAndTakeActions")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UseOnMountAndTakeActions
{
    [FieldOffset(24)] public NullablePointer[] predicates;
    [FieldOffset(40)] public Usage[] usages;
    [FieldOffset(56)] public string useCursor;
    [FieldOffset(68)] public TextFileRef warningUseText;
    [FieldOffset(84)] public bool multipleUse;
    [FieldOffset(85)] public bool userChoice;
    [StructSize(60)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Usage
    {
        [FieldOffset(4)] public ResourcePointer[] allowedMounts;
        [FieldOffset(20)] public int consumeUsedItem;
        [FieldOffset(24)] public NullablePointer mountPredicate;
        [FieldOffset(28)] public string sysName;
        [FieldOffset(40)] public NullablePointer usedItemPredicate;
        [FieldOffset(44)] public TextFileRef warningUseText;
    }
}