// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(80)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VICHideGeosets
{
    [FieldOffset(28)] public HiddenGeosets hiddenGeosets;

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class HiddenGeosets
    {
        [FieldOffset(4)] public string[] female;
        [FieldOffset(20)] public string[] male;
        [FieldOffset(36)] public string[] unisex;
    }
}
