// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(52)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VICReplaceTexture
{
    [FieldOffset(28)] public string[] shapeName;
    [FieldOffset(44)] public ResourcePointer texture;
}