// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(52)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VICSelectComponentByGuildCurrency
{
    [FieldOffset(24)] public Case[] cases;
    [FieldOffset(44)] public ResourcePointer currency;

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Case
    {
        [FieldOffset(4)] public NullablePointer[] dynamicComponents;
        [FieldOffset(20)] public int maxValue;
        [FieldOffset(24)] public int minValue;
        [FieldOffset(28)] public NullablePointer[] staticComponents;
    }
}
