// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(196)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisItemEffectsRanged
{
    [FieldOffset(24)] public string attachArrowLocatorInItem;
    //TODO: ENUM
    [FieldOffset(36)] public int[] attackAnimation;
    //TODO: ENUM
    [FieldOffset(52)] public int[] cheapShotAnimation;
    //TODO: ENUM
    [FieldOffset(68)] public int[] cheapShotStartAnimation;
    [FieldOffset(84)] public ResourcePointer explosion;
    [FieldOffset(92)] public LoadHoldAnimation[] holdAnimations;
    //TODO: ENUM
    [FieldOffset(108)] public int[] loadAnimation;
    [FieldOffset(124)] public LoadHoldAnimation[] loadHoldAnimations;
    [FieldOffset(140)] public ResourcePointer projectile;
    //TODO: ENUM
    [FieldOffset(148)] public int[] rapidFireAnimation;
    //TODO: ENUM
    [FieldOffset(164)] public int[] readyAnimation;
    //TODO: ENUM
    [FieldOffset(180)] public int rotateArrowInItem;
    [FieldOffset(184)] public ResourcePointer script;
    [FieldOffset(192)] public bool useTakeStringInHand;
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class LoadHoldAnimation
    {
        //TODO: ENUM
        [FieldOffset(4)] public int[] animations;
        [FieldOffset(20)] public int rate;
    }
}