// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(44)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisMobModifierPet
{
    [FieldOffset(28)] public Level[] levels;

    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Level
    {
        [FieldOffset(4)] public FaceVariation[] faceVariations;
        [FieldOffset(20)] public NullablePointer playAfterChanging;
        [FieldOffset(24)] public int startLevel;
        [FieldOffset(28)] public ResourcePointer visualMob;

        [StructSize(20)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class FaceVariation
        {
            [FieldOffset(4)][XdbName("base")] public ResourcePointer @base;
            [FieldOffset(12)] public ResourcePointer level;
        }
    }
}
