// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(60)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisPointLocator
{
    [FieldOffset(20)] public Vector3 shift;
    //TODO: ENUM
    [FieldOffset(36)] public int from;
    //TODO: ENUM
    [FieldOffset(40)] public int locator;
    [FieldOffset(44)] public string locatorName;
    //TODO: ENUM
    [FieldOffset(56)] public int member;
}