// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(40)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualMobTroopExtension
{
    [FieldOffset(24)] public Member[] members;

    [StructSize(104)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Member
    {
        [FieldOffset(4)] public ResourcePointer character;
        [FieldOffset(12)] public Variation variation;

        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Variation
        {
            [FieldOffset(4)] public ResourcePointer additionalVariation;
            [FieldOffset(12)] public ResourcePointer face;
            [FieldOffset(20)] public ResourcePointer facial;
            [FieldOffset(28)] public int hairColor;
            [FieldOffset(32)] public ResourcePointer hairGeoset;
            [FieldOffset(44)] public MorphPreset morphPreset;
            [FieldOffset(64)] public int morphPresetIndex;
            [FieldOffset(68)] public ResourcePointer shoulderStone;
            [FieldOffset(76)] public int shoulderStoneColor;
            [FieldOffset(80)] public ResourcePointer skin;
            [FieldOffset(88)] public int skinColor;

            [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
            public class MorphPreset
            {
                [FieldOffset(4)] public Value[] values;

                [StructSize(16)]
                [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
                public class Value
                {
                    [FieldOffset(8)][EnumRef(typeof(Enums.ModelMorphControl))] public int controlName;
                    [FieldOffset(12)] public float value;
                }
            }
        }
    }
}

