// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(132)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualAutoLooterClass
{
    [FieldOffset(24)][EnumRef(typeof(Enums.Animations))] public int animateHide;
    [FieldOffset(28)][EnumRef(typeof(Enums.Animations))] public int animateIdle;
    [FieldOffset(32)][EnumRef(typeof(Enums.Animations))] public int animateLoot;
    [FieldOffset(36)][EnumRef(typeof(Enums.Animations))] public int animateRun;
    [FieldOffset(40)][EnumRef(typeof(Enums.Animations))] public int animateShow;
    [FieldOffset(44)] public Vector3 avatarOffset;
    [FieldOffset(56)] public float fadeInTime;
    [FieldOffset(60)] public float fadeOutTime;
    [FieldOffset(64)][EnumRef(typeof(Enums.FxLocators))] public int locator;
    [FieldOffset(68)] public string locatorName;
    [FieldOffset(80)] public Vector3 lootOffset;
    [FieldOffset(92)] public float maxRoll;
    [FieldOffset(96)] public float maxRollSpeed;
    [FieldOffset(100)] public float maxTurnSpeed;
    [FieldOffset(104)] public float minHeight;
    [FieldOffset(108)] public float rollRotationCoef;
    [FieldOffset(112)] public float rotationDistPart;
    [FieldOffset(116)] public float scale;
    [FieldOffset(120)] public float turnSpeeddownCoef;
    [FieldOffset(124)] public float turnSpeeddownLim;
    [FieldOffset(128)] public float turnSpeedownMinAngle;
}

