// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(204)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisualItemClass
{
    //TODO: ENUM
    [FieldOffset(24)] public int animationsType;
    [FieldOffset(28)] public BlockSound[] blockSounds;
    [FieldOffset(44)] public HitSound[] hitSounds;
    //TODO: ENUM
    [FieldOffset(60)] public int holdAnimation;
    [FieldOffset(64)] public ResourcePointer holdController;
    //TODO: ENUM
    [FieldOffset(72)] public int holdHand;
    [FieldOffset(76)] public Sound3D missSound;
    [FieldOffset(104)] public TextFileRef name;
    [FieldOffset(120)] public ResourcePointer replacement;
    [FieldOffset(128)] public string storeInLocator;
    [FieldOffset(140)] public string storeInLocatorOffHand;
    [FieldOffset(152)] public Throwing throwing;
    [FieldOffset(168)] public NullablePointer visItemEffects;
    [FieldOffset(172)] public Sound3D whooshSound;
    [FieldOffset(200)] public bool hideIfStored;
    [FieldOffset(201)] public bool storeAsDualWeapon;
    [FieldOffset(202)] public bool storeUpToUp;
    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class HitSound
    {
        //TODO: ENUM
        [FieldOffset(4)] public int hitMaterial;
        [FieldOffset(8)] public Sound3D hitSound;
    }
    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class BlockSound
    {
        //TODO: ENUM
        [FieldOffset(4)] public int shieldMaterial;
        [FieldOffset(8)] public Sound3D shieldSound;
    }
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Throwing
    {
        [FieldOffset(4)] public ResourcePointer projectile;
        //TODO: ENUM
        [FieldOffset(12)] public int throwAnimation;
    }
}