// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(448)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WidgetEditBox
{
    [FieldOffset(24)][XdbName("BackLayer")] public ResourcePointer backLayer;
    [FieldOffset(32)][XdbName("Children")] public ResourcePointer[] children;
    [FieldOffset(48)][XdbName("FrontLayer")] public ResourcePointer frontLayer;
    [FieldOffset(56)][XdbName("Name")] public string name;
    [FieldOffset(72)][XdbName("Placement")] public Placement placement;
    [FieldOffset(148)][XdbName("Priority")] public int priority;
    [FieldOffset(152)][XdbName("TabOrder")] public int tabOrder;
    [FieldOffset(156)] public BindSection[] bindSections;
    [FieldOffset(172)] public float fade;
    [FieldOffset(176)] public string forceReactionOnPointing;
    [FieldOffset(188)] public ResourcePointer pickMask;
    [FieldOffset(196)] public string reactionOnPointing;
    [FieldOffset(208)] public string reactionWheelDown;
    [FieldOffset(220)] public string reactionWheelUp;
    [FieldOffset(232)] public ResourcePointer soundHide;
    [FieldOffset(240)] public ResourcePointer soundShow;
    [FieldOffset(248)] public ResourcePointer textureMask;
    [FieldOffset(256)][XdbName("Enabled")] public bool enabled;
    [FieldOffset(257)][XdbName("IgnoreDblClick")] public bool ignoreDblClick;
    [FieldOffset(258)][XdbName("PickChildrenOnly")] public bool pickChildrenOnly;
    [FieldOffset(259)][XdbName("TransparentInput")] public bool transparentInput;
    [FieldOffset(260)][XdbName("Visible")] public bool visible;
    [FieldOffset(261)] public bool clipContent;
    [FieldOffset(262)] public bool forceWheel;
    [FieldOffset(263)] public bool isProtected;
    [FieldOffset(268)][XdbName("Cursor1Layer")] public ResourcePointer cursor1Layer;
    [FieldOffset(276)][XdbName("Cursor2Layer")] public ResourcePointer cursor2Layer;
    [FieldOffset(284)][XdbName("CursorChangeTimeMs")] public int cursorChangeTimeMs;
    [FieldOffset(288)][XdbName("CursorWidth")] public int cursorWidth;
    [FieldOffset(292)][XdbName("ReactionChanged")] public string reactionChanged;
    [FieldOffset(304)][XdbName("ReactionEsc")] public string reactionEsc;
    [FieldOffset(316)][XdbName("TextStyle")] public TextStyle textStyle;
    [FieldOffset(340)] public string filterAlias;
    [FieldOffset(352)] public WString globalClassName;
    [FieldOffset(364)] public int maxSymbolsCount;
    [FieldOffset(368)] public ResourcePointer placeholder;
    [FieldOffset(376)] public string reactionCapsLock;
    [FieldOffset(388)] public string reactionFocusChanged;
    [FieldOffset(400)] public string reactionPaste;
    [FieldOffset(412)] public WString selectionClassName;
    [FieldOffset(424)] public ResourcePointer selectionLayer;
    [FieldOffset(432)] public bool canPaste;
    [FieldOffset(440)] public ResourcePointer scrollBar;

    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class BindSection
    {
        [FieldOffset(4)] public string bindSection;
        [FieldOffset(16)] public string[] bindedReactions;
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Placement
    {
        [FieldOffset(0)][XdbName("X")] public Y x;
        [FieldOffset(24)][XdbName("Y")] public Y y;
        [FieldOffset(48)] public ResourcePointer sizingWidget;
        [FieldOffset(56)] public ResourcePointer[] sizingWidgets;
        [FieldOffset(72)][XdbName("QuantumScale")] public bool quantumScale;

        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Y
        {
            [FieldOffset(4)][XdbName("Align")][EnumRef(typeof(Enums.WidgetAlign))] public int align;
            [FieldOffset(8)][XdbName("HighPos")] public float highPos;
            [FieldOffset(12)][XdbName("Pos")] public float pos;
            [FieldOffset(16)][XdbName("Size")] public float size;
            [FieldOffset(20)][XdbName("Sizing")][EnumRef(typeof(Enums.WidgetSizing))] public int sizing;
        }
    }

    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextStyle
    {
        [FieldOffset(4)][XdbName("Align")][EnumRef(typeof(Enums.AlignY))] public int align;
        [FieldOffset(8)][EnumRef(typeof(Enums.BlendEffectType))] public int blendEffect;
        [FieldOffset(12)] public float lineSpacing;
        [FieldOffset(16)] public bool ellipsis;
        [FieldOffset(17)] public bool multiline;
        [FieldOffset(18)] public bool showClippedLine;
        [FieldOffset(19)] public bool showClippedSymbol;
        [FieldOffset(20)] public bool wrapText;
    }
}
