// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V14_0_01_71;

[StructSize(132)]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ZoneInfo
{
    [FieldOffset(20)] public bool isInternal;
    [FieldOffset(28)] public Sound2D ambience;
    [FieldOffset(52)] public AmbienceParameter[] ambienceParameters;
    [FieldOffset(68)] public int ambienceTimeout;
    [FieldOffset(72)] public float hiCutFreq;
    [FieldOffset(76)] public ResourcePointer lights;
    [FieldOffset(84)] public Sound2D music;
    [FieldOffset(108)] public Sound2D reverbPreset;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class AmbienceParameter
    {
        [FieldOffset(4)] public ResourcePointer parameter;
        [FieldOffset(12)] public float value;
    }
}
