// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(68)]
[XdbName("gameMechanics.constructor.basicInterfaces.ActionGroup")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ActionGroup
{
    [FieldOffset(24)] public string sysName;
    [FieldOffset(36)] public ResourcePointer[] actions;
    [FieldOffset(52)][XdbName("Name")] public TextFileRef name;
}
