// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(164)]
[XdbName("AnimationProperties")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AnimationProperties
{
    [FieldOffset(24)] public float walkBackwards;
    [FieldOffset(28)] public float walk;
    [FieldOffset(32)] public TargetTrackingParams targetTrackingParams;
    [FieldOffset(92)] public float swimHeight;
    [FieldOffset(96)] public string spineBoneName;
    [FieldOffset(108)] public SpecialShuffleParams specialShuffleParams;
    [FieldOffset(120)] public float run;
    [FieldOffset(124)] public bool moveAnimationsNoScale;
    [FieldOffset(128)] public float maxHeadAngle;
    [FieldOffset(132)] public float legRunTurnTime;
    [FieldOffset(136)] public float legAlignTime;

    [FieldOffset(140)]
    [EnumRef(typeof(Enums.CreatureKind))]
    public int kind;

    [FieldOffset(144)] public float headTurnTime;
    [FieldOffset(148)] public string headBoneName;
    [FieldOffset(160)] public bool groundNormalByBoundingBox;
    [FieldOffset(161)] public bool finishMoveAnimation;
    [FieldOffset(162)] public bool canWalkBackwards;

    [StructSize(60)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TargetTrackingParams
    {
        [FieldOffset(4)]
        [EnumRef(typeof(Enums.Bone))]
        public int verticalRotate;

        [FieldOffset(8)] public bool useInEveryAnimation;
        [FieldOffset(9)] public bool use;
        [FieldOffset(12)] public string targetBoneName;
        [FieldOffset(24)] public float maxHeadAngleToUp;
        [FieldOffset(28)] public float maxHeadAngleToSide;
        [FieldOffset(32)] public float maxHeadAngleToDown;
        [FieldOffset(36)] public bool ingnoreRotateToTarget;

        [FieldOffset(40)]
        [EnumRef(typeof(Enums.Bone))]
        public int horizontalRotate;

        [FieldOffset(44)]
        [EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)]
        public int[] addedToUseAnimations;
    }

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SpecialShuffleParams
    {
        [FieldOffset(4)] public float minChangeVelocityAngle;
        [FieldOffset(8)] public float minChangeRotationAngle;
    }
}
