// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(56)]
[XdbName("gameMechanics.elements.skills.armorCraft.ArmorCraftRecipeInfo")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ArmorCraftRecipeInfo
{
    [FieldOffset(24)] public ResourcePointer resultGreen;
    [FieldOffset(32)] public ResourcePointer resultBlue;
    [FieldOffset(40)] public Item[] items;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Item
    {
        [FieldOffset(4)] public ResourcePointer item;
        [FieldOffset(12)] public int count;
    }
}
