// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(116)]
[XdbName("AstralObject")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class AstralObject
{
    [FieldOffset(24)] public RunWaveInfo runWaveInfo;
    [FieldOffset(56)] public Part[] parts;
    [FieldOffset(72)] public float maxSize;
    [FieldOffset(76)] public float forceFieldRadius;
    [FieldOffset(80)] public ResourcePointer flareTexture;
    [FieldOffset(88)] public FlareFade flareFade;
    [FieldOffset(100)] public FlareFade effectFade;
    [FieldOffset(112)] public float astralRadius;

    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RunWaveInfo
    {
        [FieldOffset(4)] public ResourcePointer visObject;
        [FieldOffset(12)] public float speedStart;
        [FieldOffset(16)] public float speedEnd;
        [FieldOffset(20)] public float scale;
        [FieldOffset(24)] public float runWaveRadius;
        [FieldOffset(28)] public float elastic;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Part
    {
        [FieldOffset(4)] public ResourcePointer visObject;
        [FieldOffset(12)] public float scale;
        [FieldOffset(16)] public float freezeDistance;
    }

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class FlareFade
    {
        [FieldOffset(4)] public float start;
        [FieldOffset(8)] public float end;
    }
}
