// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(52)]
[XdbName("CameraShakeParameters")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CameraShakeParameters
{
    [FieldOffset(24)] public float timeScale;
    [FieldOffset(28)] public float minRadius;
    [FieldOffset(32)] public float maxRadius;
    [FieldOffset(36)] public bool looped;
    [FieldOffset(40)] public ResourcePointer animation;
    [FieldOffset(48)] public float amplitudeScale;
}
