// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(56)]
[XdbName("CharacterAnimationsGroup")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterAnimationsGroup
{
    [FieldOffset(24)] public CharacterAnimation[] characterAnimations;
    [FieldOffset(40)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int[] allCharacterAnimations;
    
    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CharacterAnimation
    {
        [FieldOffset(4)] public ResourcePointer character;
        [FieldOffset(12)][EnumRef(typeof(Enums.Animations), UseSourceOnCast = true)] public int[] animations;
    }
}
