// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(72)]
[XdbName("gameMechanics.world.avatar.CharacterRace")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class CharacterRace
{
    [FieldOffset(24)] public string sysName;
    [FieldOffset(36)] public RaceSexDesc[] raceSexDescs;
    [FieldOffset(52)] public TextFileRef name;
    [FieldOffset(68)] public float corpulence;
    
    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RaceSexDesc
    {
        [FieldOffset(4)][EnumRef(typeof(Enums.Sex))] public int sex;
        [FieldOffset(8)] public TextFileRef name;
    }
}
