// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(64)]
[XdbName("DeviceFixedPointProjectileAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class DeviceFixedPointProjectileAction
{
    [FieldOffset(28)] public float theGe;
    [FieldOffset(32)] public ResourcePointer projectileFx;
    [FieldOffset(40)] public Line[] lines;
    [FieldOffset(56)] public ResourcePointer explosionFx;

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Line
    {
        [FieldOffset(4)] public int throwDuration;
        [FieldOffset(8)] public int startPointIndex;
        [FieldOffset(12)] public int endPointIndex;
    }
}
