// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(60)]
[XdbName("FlareEffect")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class FlareEffect
{
    [FieldOffset(24)] public bool visualOccluder;
    [FieldOffset(28)] public float transparencyModifier;
    [FieldOffset(32)] public float sizeModifier;
    [FieldOffset(36)] public float occlusionSize;
    [FieldOffset(40)] public Flare[] flares;
    [FieldOffset(56)] public float fadeSpeed;

    [StructSize(28)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Flare
    {
        [FieldOffset(4)] public float transparency;
        [FieldOffset(8)] public ResourcePointer texture;
        [FieldOffset(16)] public float size;
        [FieldOffset(20)] public float screenSizeBoost;
        [FieldOffset(24)] public float screenOffset;
    }
}
