// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(192)]
[XdbName("GameViewScene")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class GameViewScene
{
    [FieldOffset(28)] public Place place;
    [FieldOffset(80)] public Path[] paths;
    [FieldOffset(96)] public Mob[] mobs;
    [FieldOffset(112)] public Device[] devices;
    [FieldOffset(132)] public CameraPlacement cameraPlacement;

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Place
    {
        [FieldOffset(4)] public double z;
        [FieldOffset(12)] public float yaw;
        [FieldOffset(20)] public double y;
        [FieldOffset(28)] public double x;
        [FieldOffset(36)] public bool notLoadMap;
        [FieldOffset(40)] public ResourcePointer map;
        [FieldOffset(48)] public float gfxMinimizeCoeff;
    }

    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Path
    {
        [FieldOffset(4)] public float yaw;
        [FieldOffset(8)] public string scriptID;
        [FieldOffset(20)] public Vector3[] points;
    }

    [StructSize(72)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Mob
    {
        [FieldOffset(4)] public float yaw;
        [FieldOffset(8)] public ResourcePointer visualMob;
        [FieldOffset(16)] public string scriptID;
        [FieldOffset(28)] public Vector3 offset;
        [FieldOffset(40)] public bool isDisableToRotate;
        [FieldOffset(41)] public bool isDead;
        [FieldOffset(44)] public string groupName;
        [FieldOffset(56)] public ResourcePointer[] collectionEditions;
    }

    [StructSize(44)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Device
    {
        [FieldOffset(4)] public float yaw;
        [FieldOffset(8)] public int visualState;
        [FieldOffset(12)] public string scriptID;
        [FieldOffset(24)] public Vector3 offset;
        [FieldOffset(36)] public ResourcePointer device;
    }

    [StructSize(60)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class CameraPlacement
    {
        [FieldOffset(4)] public double z;
        [FieldOffset(12)] public float yaw;
        [FieldOffset(20)] public double y;
        [FieldOffset(28)] public double x;
        [FieldOffset(36)] public float roll;
        [FieldOffset(40)] public float pitch;
        [FieldOffset(44)] public float distance;
        [FieldOffset(56)] public bool use;
        [FieldOffset(57)] public bool autoSave;
    }
}
