// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(84)]
[XdbName("gameMechanics.interactions.common.Interactions")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class Interactions
{
    [FieldOffset(20)] public ResourcePointer vendorTable;
    [FieldOffset(28)] public NullablePointer trainer;
    [FieldOffset(32)] public NullablePointer teleportMaster;
    [FieldOffset(36)] public NullablePointer recreationalArea;
    [FieldOffset(40)] public bool isMailBox;
    [FieldOffset(41)] public bool isBankAccessor;
    [FieldOffset(44)][EnumRef(typeof(Enums.ExtendedType))] public int[] extended;
    [FieldOffset(60)] public Cue[] cues;
    [FieldOffset(76)] public ResourcePointer auction;

    [StructSize(4)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Cue
    {
    }
}
