// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(60)]
[XdbName("gameMechanics.constructor.schemes.item.ItemQuality")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ItemQuality
{
    [FieldOffset(28)][EnumRef(typeof(Enums.QualityEnum))] public int quality;
    [FieldOffset(32)] public ResourcePointer lootBagVisObject;
    [FieldOffset(40)] public float budgetMod;
    [FieldOffset(44)] public ResourcePointer[] all;
}
