// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(88)]
[XdbName("MobEventsScripts")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class MobEventsScripts
{
    [FieldOffset(24)] public NullablePointer preAggroScript;
    [FieldOffset(28)] public MobHealth mobHealth;
    [FieldOffset(40)] public IdleScriptParams idleScriptParams;
    [FieldOffset(56)] public MobHealth enemyHealth;
    [FieldOffset(68)] public DeathScriptParams deathScriptParams;
    [FieldOffset(84)] public NullablePointer aggroScript;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class MobHealth
    {
        [FieldOffset(4)] public NullablePointer script;
        [FieldOffset(8)] public float health;
    }

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class IdleScriptParams
    {
        [FieldOffset(4)] public NullablePointer script;
        [FieldOffset(8)] public float idlePeriodMin;
        [FieldOffset(12)] public float idlePeriodMax;
    }

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DeathScriptParams
    {
        [FieldOffset(4)] public NullablePointer scriptIfWasDead;
        [FieldOffset(8)] public NullablePointer script;
        [FieldOffset(12)] public bool autoplayDeathAnim;
    }
}
