// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(152)]
[XdbName("gameMechanics.world.mob.MobWorld")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class MobWorld
{
    [FieldOffset(24)] public NullablePointer[] parts;
    [FieldOffset(44)] public TextFileRef name;
    [FieldOffset(60)] public float corpulence;
    [FieldOffset(68)] public ResourcePointer visMob;
    [FieldOffset(76)] public bool usesWeapon;
    [FieldOffset(80)] public TextFileRef title;
    [FieldOffset(96)] public ResourcePointer thoughtsPool;
    [FieldOffset(104)] public bool removeFromUI;
    [FieldOffset(108)] public ResourcePointer quality;
    [FieldOffset(116)] public ResourcePointer modifier;
    [FieldOffset(124)] public ResourcePointer mobEventsScripts;
    [FieldOffset(132)] public int levelMin;
    [FieldOffset(136)] public ResourcePointer kind;
    [FieldOffset(144)] public NullablePointer interactions;
    [FieldOffset(148)] public bool canTalkWithEnemy;
}
