// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(184)]
[XdbName("gameMechanics.world.rules.RuleResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class RuleResource
{
    [FieldOffset(24)] public ResourcePointer zone;
    [FieldOffset(32)][EnumRef(typeof(Enums.RuleType))] public int[] types;
    [FieldOffset(48)] public ResourcePointer timeTable;
    [FieldOffset(56)] public Reward reward;
    [FieldOffset(136)] public int rating;
    [FieldOffset(140)] public TextFileRef name;
    [FieldOffset(156)] public int level;
    [FieldOffset(160)] public ResourcePointer faction;
    [FieldOffset(168)] public TextFileRef description;
    
    [StructSize(80)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Reward
    {
        [FieldOffset(4)] public Reputation[] reputations;
        [FieldOffset(20)] public int money;
        [FieldOffset(24)] public MandatoryItem[] mandatoryItems;
        [FieldOffset(40)] public int honor;
        [FieldOffset(44)] public int experience;
        [FieldOffset(48)] public Currencie[] currencies;
        [FieldOffset(64)] public MandatoryItem[] alternativeItems;
        
        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Reputation
        {
            [FieldOffset(4)] public int value;
            [FieldOffset(8)] public ResourcePointer faction;
        }
        
        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class MandatoryItem
        {
            [FieldOffset(4)] public NullablePointer predicate;
            [FieldOffset(8)] public int number;
            [FieldOffset(12)] public ResourcePointer item;
            [FieldOffset(20)] public bool hidden;
        }
        
        [StructSize(16)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Currencie
        {
            [FieldOffset(4)] public int value;
            [FieldOffset(8)] public ResourcePointer currency;
        }
    }
}
