// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(40)]
[XdbName("gameMechanics.constructor.schemes.item.RuneSlot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class RuneSlot
{
    [FieldOffset(24)] public RuneLevels runeLevels;
    [FieldOffset(36)] public bool hasInitialRune;

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class RuneLevels
    {
        [FieldOffset(4)] public int min;
        [FieldOffset(8)] public int max;
    }
}
