// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(92)]
[XdbName("gameMechanics.world.device.scaner.ScanerDeviceAction")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ScanerDeviceAction
{
    [FieldOffset(24)] public NullablePointer[] userConditions;
    [FieldOffset(40)] public TextFileRef name;
    [FieldOffset(56)] public ResourcePointer image;
    [FieldOffset(64)] public TextFileRef description;
    [FieldOffset(84)][EnumRef(typeof(Enums.Operation))] public int operation;
    [FieldOffset(88)] public float costMultiplier;
}
