// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(40)]
[XdbName("SFXTable")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SFXTable
{
    [FieldOffset(24)] public SfxItem[] sfxItems;
    
    [StructSize(56)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SfxItem
    {
        [FieldOffset(4)] public Sound whooshSound;
        [FieldOffset(28)][EnumRef(typeof(Enums.SFXMaterial))] public int material;
        [FieldOffset(32)] public Sound hitSound;
    }
}
