// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(112)]
[XdbName("gameMechanics.world.ship.device.ShipDeviceResource")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class ShipDeviceResource
{
    [FieldOffset(24)] public ResourcePointer visualItem;
    [FieldOffset(32)] public SpectificItem[] spectificItems;
    [FieldOffset(48)] public ResourcePointer quality;
    [FieldOffset(56)] public TextFileRef name;
    [FieldOffset(72)] public ResourcePointer image;
    [FieldOffset(80)] public TextFileRef description;
    [FieldOffset(96)] public ClientDevice[] clientDevices;

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SpectificItem
    {
        [FieldOffset(4)] public ResourcePointer ship;
        [FieldOffset(12)] public ResourcePointer resource;
    }

    [StructSize(16)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class ClientDevice
    {
        [FieldOffset(4)]
        [EnumRef(typeof(Enums.SlotName))]
        public int slotName;

        [FieldOffset(8)] public ResourcePointer resource;
    }
}
