// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(44)]
[XdbName("SkyMesh")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SkyMesh
{
    [FieldOffset(24)] public Part[] parts;
    [FieldOffset(40)] public float noiseFactor;

    [StructSize(164)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Part
    {
        [FieldOffset(4)] public Vector3 worldCoord;
        [FieldOffset(16)] public bool useWorldCoord;
        [FieldOffset(17)] public bool show;
        [FieldOffset(20)] public ResourcePointer geometry;
        [FieldOffset(28)] public float fovFactor;
        [FieldOffset(32)] public NullablePointer[] effects;
        [FieldOffset(48)] public Controller[] controllers;
        [FieldOffset(64)] public float colorFactor;
        [FieldOffset(68)] public Color2 color2;
        [FieldOffset(96)] public Color2 color1;
        [FieldOffset(124)] public Color2 color0;
        [FieldOffset(152)] public ResourcePointer animation;
        [FieldOffset(160)] public int ambientColor;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Controller
        {
            [FieldOffset(4)] public float speed;
            [FieldOffset(8)] public ResourcePointer controller;
            [FieldOffset(16)] public ResourcePointer animation;
        }

        [StructSize(28)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Color2
        {
            [FieldOffset(4)] public float facingValueSun;
            [FieldOffset(8)] public float facingValueSky;
            [FieldOffset(12)][XdbName("GradientSunLo")] public int gradientSunLo;
            [FieldOffset(16)][XdbName("GradientSunHi")] public int gradientSunHi;
            [FieldOffset(20)][XdbName("GradientSkyLo")] public int gradientSkyLo;
            [FieldOffset(24)][XdbName("GradientSkyHi")] public int gradientSkyHi;
        }
    }
}
