// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(72)]
[XdbName("SlashCommands")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class SlashCommands
{
    [FieldOffset(24)] public TextFileRef slashPrefixes;
    [FieldOffset(40)] public EmoteCommand[] emoteCommands;
    [FieldOffset(56)] public Command[] commands;

    [StructSize(96)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class EmoteCommand
    {
        [FieldOffset(4)] public ResourcePointer script;
        [FieldOffset(12)] public TextFileRef name;
        [FieldOffset(28)] public TextFileRef description;
        [FieldOffset(44)] public Command command;

        [StructSize(52)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Command
        {
            [FieldOffset(4)] public TextFileRef prefix;
            [FieldOffset(20)] public string id;
            [FieldOffset(32)] public int argCount;
            [FieldOffset(36)] public TextFileRef aliases;
        }
    }

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Command
    {
        [FieldOffset(4)] public TextFileRef prefix;
        [FieldOffset(20)] public string id;
        [FieldOffset(32)] public int argCount;
        [FieldOffset(36)] public TextFileRef aliases;
    }
}
