// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(64)]
[XdbName("TextureSingleElement")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TextureSingleElement
{
    [FieldOffset(24)] public int y;
    [FieldOffset(28)] public int x;
    [FieldOffset(32)] public int width;
    [FieldOffset(36)] public FileRef sourceFile;
    [FieldOffset(48)] public int height;
    [FieldOffset(52)] public int crc;
    [FieldOffset(56)] public ResourcePointer atlas;
}
