// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(48)]
[XdbName("TextureAtlas")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class TextureAtlas
{
    [FieldOffset(24)] public Source[] sources;
    [FieldOffset(40)] public ResourcePointer combinedTexture;

    [StructSize(48)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Source
    {
        [FieldOffset(4)] public float yCoeffRGB;
        [FieldOffset(8)] public float yCoeffA;
        [FieldOffset(12)] public int y;
        [FieldOffset(16)] public float xCoeffRGB;
        [FieldOffset(20)] public float xCoeffA;
        [FieldOffset(24)] public int x;
        [FieldOffset(28)] public int width;
        [FieldOffset(32)] public string name;
        [FieldOffset(44)] public int height;
    }
}
