// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(228)]
[XdbName("UIAddon")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UIAddon
{
    [FieldOffset(24)] public ResourcePointer visObjects;
    [FieldOffset(32)] public TexturesGroup[] texturesGroups;
    [FieldOffset(48)] public ResourcePointer textures;
    [FieldOffset(56)] public TextsGroup[] textsGroups;
    [FieldOffset(72)] public ResourcePointer texts;
    [FieldOffset(80)] public SoundsGroup[] soundsGroups;
    [FieldOffset(96)] public ResourcePointer sounds;
    [FieldOffset(104)] public TextFileRef localizedNameFileRef;
    [FieldOffset(120)] public TextFileRef localizedDescFileRef;
    [FieldOffset(136)] public ResourcePointer decalObjects;
    [FieldOffset(144)] public ResourcePointer aliasVisObjects;
    [FieldOffset(152)] public string[] addonGroups;

    [FieldOffset(168)]
    [XdbName("ScriptFileRefs")]
    public FileRef[] scriptFileRefs;

    [FieldOffset(184)][XdbName("Name")] public string name;

    [FieldOffset(196)]
    [XdbName("MainFormId")]
    public string mainFormId;

    [FieldOffset(208)][XdbName("Forms")] public Form[] forms;

    [FieldOffset(224)]
    [XdbName("AutoStart")]
    public bool autoStart;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TexturesGroup
    {
        [FieldOffset(4)] public ResourcePointer textures;
        [FieldOffset(12)] public string groupName;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextsGroup
    {
        [FieldOffset(4)] public ResourcePointer texts;
        [FieldOffset(12)] public string groupName;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SoundsGroup
    {
        [FieldOffset(4)] public ResourcePointer sounds;
        [FieldOffset(12)] public string groupName;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Form
    {
        [FieldOffset(4)][XdbName("Id")] public string id;
        [FieldOffset(16)][XdbName("Form")] public ResourcePointer form;
    }
}
