// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(312)]
[XdbName("UIGameRoot")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UIGameRoot
{
    [FieldOffset(24)] public ResourcePointer urls;
    [FieldOffset(32)] public ResourcePointer uioptions;
    [FieldOffset(40)] public ResourcePointer uiBinds;
    [FieldOffset(48)] public TextFormatInfo textFormatInfo;
    [FieldOffset(100)] public ResourcePointer textFiltersList;
    [FieldOffset(108)] public ResourcePointer systemSpec;
    [FieldOffset(116)] public ResourcePointer slonRoot;
    [FieldOffset(124)] public ResourcePointer sheathShowRanged;
    [FieldOffset(132)] public ResourcePointer sheathShowMelee;
    [FieldOffset(140)] public ResourcePointer sheathHide;
    [FieldOffset(148)] public QuantumScale[] quantumScales;
    [FieldOffset(164)] public float pickRangePrecise;
    [FieldOffset(168)] public float pickRangeBox;
    [FieldOffset(172)] public DefaultWidgetsSounds defaultWidgetsSounds;
    [FieldOffset(192)] public ResourcePointer cursorTable;
    [FieldOffset(200)] public ResourcePointer characterScenes;

    [FieldOffset(208)]
    [XdbName("Widgets")]
    public Widget[] widgets;

    [FieldOffset(224)]
    [XdbName("StyleSheets")]
    public ResourcePointer[] styleSheets;

    [FieldOffset(240)][XdbName("States")] public ResourcePointer[] states;

    [FieldOffset(256)]
    [XdbName("Mission")]
    public ResourcePointer mission;

    [FieldOffset(264)][XdbName("Forms")] public Form[] forms;

    [FieldOffset(280)]
    [XdbName("FontAliases")]
    public ResourcePointer fontAliases;

    [FieldOffset(288)]
    [XdbName("DefaultFont")]
    public string defaultFont;

    [FieldOffset(300)]
    [XdbName("AddonScriptBaseFileRef")]
    public FileRef addonScriptBaseFileRef;

    [StructSize(52)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextFormatInfo
    {
        [FieldOffset(4)] public TextFileRef thousandMark;
        [FieldOffset(20)] public TextFileRef digitsGroupMark;
        [FieldOffset(36)] public TextFileRef decimalMark;
    }

    [StructSize(12)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class QuantumScale
    {
        [FieldOffset(4)] public float quantumScale;
        [FieldOffset(8)] public float actualScale;
    }

    [StructSize(20)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class DefaultWidgetsSounds
    {
        [FieldOffset(4)] public ResourcePointer buttonSoundPress;
        [FieldOffset(12)] public ResourcePointer buttonSoundOver;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Widget
    {
        [FieldOffset(4)][XdbName("Widget")] public ResourcePointer widget;
        [FieldOffset(12)][XdbName("Id")] public string id;
    }

    [StructSize(40)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Form
    {
        [FieldOffset(4)][XdbName("Widgets")] public Widget[] widgets;
        [FieldOffset(20)][XdbName("Id")] public string id;
        [FieldOffset(32)][XdbName("Form")] public ResourcePointer form;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Widget
        {
            [FieldOffset(4)][XdbName("Widget")] public ResourcePointer widget;
            [FieldOffset(12)][XdbName("Id")] public string id;
        }
    }
}
