// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable
using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(168)]
[XdbName("UIState")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class UIState
{
    [FieldOffset(24)] public ResourcePointer visObjects;
    [FieldOffset(32)] public TexturesGroup[] texturesGroups;
    [FieldOffset(48)] public ResourcePointer textures;
    [FieldOffset(56)] public TextsGroup[] textsGroups;
    [FieldOffset(72)] public ResourcePointer texts;
    [FieldOffset(80)] public SoundsGroup[] soundsGroups;
    [FieldOffset(96)] public ResourcePointer sounds;
    [FieldOffset(104)] public ResourcePointer decalObjects;
    [FieldOffset(112)] public ResourcePointer aliasVisObjects;
    [FieldOffset(120)][XdbName("Name")] public string name;
    [FieldOffset(132)][XdbName("MainForm")] public ResourcePointer mainForm;
    [FieldOffset(140)][XdbName("MainAddonName")] public string mainAddonName;
    [FieldOffset(152)][XdbName("Addons")] public ResourcePointer[] addons;

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TexturesGroup
    {
        [FieldOffset(4)] public ResourcePointer textures;
        [FieldOffset(12)] public string groupName;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class TextsGroup
    {
        [FieldOffset(4)] public ResourcePointer texts;
        [FieldOffset(12)] public string groupName;
    }

    [StructSize(24)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class SoundsGroup
    {
        [FieldOffset(4)] public ResourcePointer sounds;
        [FieldOffset(12)] public string groupName;
    }
}
