// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(48)]
[XdbName("VisActionChangeVisObject")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class VisActionChangeVisObject
{
    [FieldOffset(20)] public string visActionID;
    [FieldOffset(36)] public ResourcePointer newVisMob;
    [FieldOffset(44)] public bool getDress;
    [FieldOffset(45)] public bool getBody;
}
