// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------

#nullable disable

using System.Numerics;
using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;
using JetBrains.Annotations;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(288)]
[XdbName("WidgetConsole")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WidgetConsole
{
    [FieldOffset(24)] public ResourcePointer textureMask;
    [FieldOffset(32)] public ResourcePointer soundShow;
    [FieldOffset(40)] public ResourcePointer soundHide;
    [FieldOffset(48)] public string reactionOnPointing;
    [FieldOffset(60)] public ResourcePointer pickMask;
    [FieldOffset(68)] public string forceReactionOnPointing;
    [FieldOffset(80)] public float fade;
    [FieldOffset(84)] public bool clipContent;
    [FieldOffset(88)] public BindSection[] bindSections;

    [FieldOffset(104)]
    [XdbName("Visible")]
    public bool visible;

    [FieldOffset(105)]
    [XdbName("TransparentInput")]
    public bool transparentInput;

    [FieldOffset(108)]
    [XdbName("TabOrder")]
    public int tabOrder;

    [FieldOffset(112)]
    [XdbName("Priority")]
    public int priority;

    [FieldOffset(116)]
    [XdbName("Placement")]
    public Placement placement;

    [FieldOffset(196)]
    [XdbName("PickChildrenOnly")]
    public bool pickChildrenOnly;

    [FieldOffset(200)][XdbName("Name")] public string name;

    [FieldOffset(212)]
    [XdbName("IgnoreDblClick")]
    public bool ignoreDblClick;

    [FieldOffset(216)]
    [XdbName("FrontLayer")]
    public ResourcePointer frontLayer;

    [FieldOffset(224)]
    [XdbName("Enabled")]
    public bool enabled;

    [FieldOffset(228)]
    [XdbName("Children")]
    public ResourcePointer[] children;

    [FieldOffset(244)]
    [XdbName("BackLayer")]
    public ResourcePointer backLayer;

    [FieldOffset(256)]
    [XdbName("EditLine")]
    public ResourcePointer editLine;

    [FieldOffset(264)]
    [XdbName("ConsoleOutput")]
    public ResourcePointer consoleOutput;

    [FieldOffset(272)]
    [XdbName("BindedPriorityReactions")]
    public string[] bindedPriorityReactions;

    [StructSize(32)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class BindSection
    {
        [FieldOffset(4)] public string[] bindedReactions;
        [FieldOffset(20)] public string bindSection;
    }

    [StructSize(80)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Placement
    {
        [FieldOffset(4)] public ResourcePointer[] sizingWidgets;
        [FieldOffset(20)] public ResourcePointer sizingWidget;
        [FieldOffset(28)][XdbName("Y")] public Y y;
        [FieldOffset(52)][XdbName("X")] public Y x;

        [FieldOffset(76)]
        [XdbName("QuantumScale")]
        public bool quantumScale;

        [StructSize(24)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Y
        {
            [FieldOffset(4)]
            [XdbName("Sizing")]
            [EnumRef(typeof(Enums.WidgetSizing))]
            public int sizing;

            [FieldOffset(8)][XdbName("Size")] public float size;
            [FieldOffset(12)][XdbName("Pos")] public float pos;
            [FieldOffset(16)][XdbName("HighPos")] public float highPos;

            [FieldOffset(20)]
            [XdbName("Align")]
            [EnumRef(typeof(Enums.WidgetAlign))]
            public int align;
        }
    }
}
