// ------------------------------------------------------------------------------
// Generated by AllodsOnlineStructCodeGenerator © paulus
// This file was autogenerated, changes can be lost if file is regenerated.
// ReSharper disable InconsistentNaming
// ------------------------------------------------------------------------------
#nullable disable

using JetBrains.Annotations;
using System.Numerics;

using AllodsOnlineEditorTools.ClientResources.DataTypes;
using AllodsOnlineEditorTools.ClientResources.Serialization;
using AllodsOnlineEditorTools.ClientResources.Serialization.Bin;
using AllodsOnlineEditorTools.ClientResources.Serialization.Xdb;
using AllodsOnlineEditorTools.ClientResources.Structs.Common;
using AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0.Enums;

namespace AllodsOnlineEditorTools.ClientResources.Structs.V1_1_02_0;

[StructSize(40)]
[XdbName("gameMechanics.constructor.schemes.quest.WorldSecrets")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
public partial class WorldSecrets
{
    [FieldOffset(24)] public Secret[] secrets;
    
    [StructSize(36)]
    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
    public class Secret
    {
        [FieldOffset(4)] public ResourcePointer secret;
        [FieldOffset(12)] public ResourcePointer image;
        [FieldOffset(20)] public Component[] components;
        
        [StructSize(36)]
        [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
        public class Component
        {
            [FieldOffset(4)] public TextFileRef text;
            [FieldOffset(20)] public ResourcePointer startQuest;
            [FieldOffset(28)] public ResourcePointer finalQuest;
        }
    }
}
